<?php
declare(strict_types=1);

// BluefinTecsMerchantServices SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

BluefinTecsMerchantServicesUtility::setRegistrar(function (BluefinTecsMerchantServicesUtility $u): void {
    $u->clean = [BluefinTecsMerchantServicesClean::class, 'call'];
    $u->done = [BluefinTecsMerchantServicesDone::class, 'call'];
    $u->make_error = [BluefinTecsMerchantServicesMakeError::class, 'call'];
    $u->feature_add = [BluefinTecsMerchantServicesFeatureAdd::class, 'call'];
    $u->feature_hook = [BluefinTecsMerchantServicesFeatureHook::class, 'call'];
    $u->feature_init = [BluefinTecsMerchantServicesFeatureInit::class, 'call'];
    $u->fetcher = [BluefinTecsMerchantServicesFetcher::class, 'call'];
    $u->make_fetch_def = [BluefinTecsMerchantServicesMakeFetchDef::class, 'call'];
    $u->make_context = [BluefinTecsMerchantServicesMakeContext::class, 'call'];
    $u->make_options = [BluefinTecsMerchantServicesMakeOptions::class, 'call'];
    $u->make_request = [BluefinTecsMerchantServicesMakeRequest::class, 'call'];
    $u->make_response = [BluefinTecsMerchantServicesMakeResponse::class, 'call'];
    $u->make_result = [BluefinTecsMerchantServicesMakeResult::class, 'call'];
    $u->make_point = [BluefinTecsMerchantServicesMakePoint::class, 'call'];
    $u->make_spec = [BluefinTecsMerchantServicesMakeSpec::class, 'call'];
    $u->make_url = [BluefinTecsMerchantServicesMakeUrl::class, 'call'];
    $u->param = [BluefinTecsMerchantServicesParam::class, 'call'];
    $u->prepare_auth = [BluefinTecsMerchantServicesPrepareAuth::class, 'call'];
    $u->prepare_body = [BluefinTecsMerchantServicesPrepareBody::class, 'call'];
    $u->prepare_headers = [BluefinTecsMerchantServicesPrepareHeaders::class, 'call'];
    $u->prepare_method = [BluefinTecsMerchantServicesPrepareMethod::class, 'call'];
    $u->prepare_params = [BluefinTecsMerchantServicesPrepareParams::class, 'call'];
    $u->prepare_path = [BluefinTecsMerchantServicesPreparePath::class, 'call'];
    $u->prepare_query = [BluefinTecsMerchantServicesPrepareQuery::class, 'call'];
    $u->graphql_body = [BluefinTecsMerchantServicesGraphql::class, 'body'];
    $u->graphql_errors = [BluefinTecsMerchantServicesGraphql::class, 'errors'];
    $u->result_basic = [BluefinTecsMerchantServicesResultBasic::class, 'call'];
    $u->result_body = [BluefinTecsMerchantServicesResultBody::class, 'call'];
    $u->result_headers = [BluefinTecsMerchantServicesResultHeaders::class, 'call'];
    $u->transform_request = [BluefinTecsMerchantServicesTransformRequest::class, 'call'];
    $u->transform_response = [BluefinTecsMerchantServicesTransformResponse::class, 'call'];
});
