-- BluefinTecsMerchantServices SDK public client (generated by @voxgig/sdkgen).
--
-- Constructors (newSdk / testSdk) and one op namespace per entity. Entities are
-- generic: every op delegates to the config-driven SdkRuntime, so the pipeline
-- is identical for every entity and every API.

import VoxgigStruct
import SdkRuntime
import SdkConfig

open VoxgigStruct

namespace Sdk

/-- Construct a live client from an options map (empty map = defaults). -/
def newSdk (options : Value) : SIO Value :=
  SdkRuntime.mkClientV options SdkConfig.configJson

/-- No-argument convenience constructor. -/
def newSdk0 : SIO Value := do newSdk (← emptyMap)

/-- Construct a test-mode client: operations are answered from an in-memory
    store seeded with the entity test data, so no server is needed. -/
def testSdk (seed : Value) (options : Value) : SIO Value :=
  SdkRuntime.mkTestClientV options SdkConfig.configJson seed

/-- Test client with default options. -/
def testSdk0 (seed : Value) : SIO Value := do testSdk seed (← emptyMap)

end Sdk

namespace Cancel_transaction
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "cancel_transaction" d co
end Cancel_transaction

namespace Check_card_black_listed
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "check_card_black_listed" d co
end Check_card_black_listed

namespace Create_product
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "create_product" d co
end Create_product

namespace Deactivate_terminal
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "deactivate_terminal" d co
end Deactivate_terminal

namespace Digital_services_api
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "digital_services_api" d co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "digital_services_api" m co
end Digital_services_api

namespace Ec_data_ecom
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "ec_data_ecom" d co
end Ec_data_ecom

namespace Ecom_parameter
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "ecom_parameter" d co
end Ecom_parameter

namespace Ecr_data
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "ecr_data" d co
end Ecr_data

namespace Emv_data
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "emv_data" d co
end Emv_data

namespace Enable_acquiring
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "enable_acquiring" d co
end Enable_acquiring

namespace Get_merchant_contract_number
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "get_merchant_contract_number" d co
end Get_merchant_contract_number

namespace Get_template_xml
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "get_template_xml" d co
end Get_template_xml

namespace Introduce_mandator
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "introduce_mandator" d co
end Introduce_mandator

namespace Introduce_package
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "introduce_package" d co
end Introduce_package

namespace Keep_alive
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "keep_alive" d co
end Keep_alive

namespace List_terminal
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "list_terminal" d co
end List_terminal

namespace Mandator_clearing_export
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "mandator_clearing_export" d co
end Mandator_clearing_export

namespace Mandator_clearing_export_download
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "mandator_clearing_export_download" d co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "mandator_clearing_export_download" m co
end Mandator_clearing_export_download

namespace Mandator_clearing_export_summary
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "mandator_clearing_export_summary" d co
end Mandator_clearing_export_summary

namespace Merchant_portal_services_api
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "merchant_portal_services_api" d co
end Merchant_portal_services_api

namespace Move_tid
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "move_tid" d co
end Move_tid

namespace Payment_manual
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "payment_manual" d co
end Payment_manual

namespace Payment_sred
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "payment_sred" d co
end Payment_sred

namespace Pre_auth_transaction_completion
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "pre_auth_transaction_completion" d co
end Pre_auth_transaction_completion

namespace Reactivate_terminal
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "reactivate_terminal" d co
end Reactivate_terminal

namespace Refund_transaction
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "refund_transaction" d co
end Refund_transaction

namespace Register_tecs_company
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "register_tecs_company" d co
end Register_tecs_company

namespace Register_terminal
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "register_terminal" d co
end Register_terminal

namespace Report_data
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "report_data" d co
end Report_data

namespace Status_transaction
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "status_transaction" d co
end Status_transaction

namespace Store_terminal_parameter
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "store_terminal_parameter" d co
end Store_terminal_parameter

namespace Terminal_id
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "terminal_id" d co
end Terminal_id

namespace Transaction_history
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "transaction_history" d co
end Transaction_history

namespace Transactions_count
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "transactions_count" d co
end Transactions_count

namespace Transactions_count_card_brand
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "transactions_count_card_brand" d co
end Transactions_count_card_brand

namespace Transactions_turnover
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "transactions_turnover" d co
end Transactions_turnover

namespace Update_merchant
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "update_merchant" d co
end Update_merchant

namespace Update_template_xml
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "update_template_xml" d co
end Update_template_xml

namespace Version
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "version" m co
end Version

