-- Typed models for the BluefinTecsMerchantServices SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class CancelTransaction
---@field acquirerId? string
---@field acquirerName? string
---@field actualBonusPoints? string
---@field amount? number
---@field authorizationCode? string
---@field balanceAmount? string
---@field cardBrand? string
---@field cardNumber? string
---@field clientId number
---@field currency string
---@field cvc? string
---@field ecData? string
---@field ecrData? string
---@field emvData? string
---@field exchangeFee? number
---@field exchangeRate? string
---@field languageCode? string
---@field merchantAddress? string
---@field merchantName? string
---@field merchantNumber? string
---@field messageType? string
---@field originalTraceNumber? number
---@field originalTransactionId? string
---@field password? string
---@field paymentReason? string
---@field receiptFooter? string
---@field receiptHeader? string
---@field receiptLayout? number
---@field receiptNumber string
---@field responseCode? number
---@field responseMessage? string
---@field serialNumber? string
---@field svc? string
---@field terminalId number
---@field terminalLocation? string
---@field traceNumber? number
---@field transactionDate? string
---@field transactionId? string
---@field txType? string
---@field userData? string

---@class CancelTransactionCreateData
---@field acquirerId? string
---@field acquirerName? string
---@field actualBonusPoints? string
---@field amount? number
---@field authorizationCode? string
---@field balanceAmount? string
---@field cardBrand? string
---@field cardNumber? string
---@field clientId number
---@field currency string
---@field cvc? string
---@field ecData? string
---@field ecrData? string
---@field emvData? string
---@field exchangeFee? number
---@field exchangeRate? string
---@field languageCode? string
---@field merchantAddress? string
---@field merchantName? string
---@field merchantNumber? string
---@field messageType? string
---@field originalTraceNumber? number
---@field originalTransactionId? string
---@field password? string
---@field paymentReason? string
---@field receiptFooter? string
---@field receiptHeader? string
---@field receiptLayout? number
---@field receiptNumber string
---@field responseCode? number
---@field responseMessage? string
---@field serialNumber? string
---@field svc? string
---@field terminalId number
---@field terminalLocation? string
---@field traceNumber? number
---@field transactionDate? string
---@field transactionId? string
---@field txType? string
---@field userData? string

---@class CheckCardBlackListed
---@field cardNo? string
---@field responseCode? number
---@field responseMessage? string

---@class CheckCardBlackListedCreateData
---@field cardNo? string
---@field responseCode? number
---@field responseMessage? string

---@class CreateProduct
---@field acquirerId? number
---@field responseCode? number
---@field responseMessage? string
---@field templateName string
---@field templateType string
---@field templateXml string
---@field terminalType string

---@class CreateProductCreateData
---@field acquirerId? number
---@field responseCode? number
---@field responseMessage? string
---@field templateName string
---@field templateType string
---@field templateXml string
---@field terminalType string

---@class DeactivateTerminal
---@field corporateUuid? string
---@field deactivationReason string
---@field packageOrderUuid? string
---@field productOrderUuid? string
---@field responseCode? number
---@field responseMessage? string
---@field terminalId number

---@class DeactivateTerminalCreateData
---@field corporateUuid? string
---@field deactivationReason string
---@field packageOrderUuid? string
---@field productOrderUuid? string
---@field responseCode? number
---@field responseMessage? string
---@field terminalId number

---@class DigitalServicesApi
---@field clearingDateFrom string
---@field clearingDateTo string
---@field responseCode? number
---@field responseMessage? string
---@field txCount? number
---@field txIdEnd? string
---@field txIdStart? string
---@field txSeqNoEnd? number
---@field txSeqNoStart? number
---@field txTotal? number

---@class DigitalServicesApiLoadMatch
---@field clearingDateFrom? string
---@field clearingDateTo? string
---@field responseCode? number
---@field responseMessage? string
---@field txCount? number
---@field txIdEnd? string
---@field txIdStart? string
---@field txSeqNoEnd? number
---@field txSeqNoStart? number
---@field txTotal? number

---@class DigitalServicesApiCreateData
---@field file_id string
---@field clearingDateFrom string
---@field clearingDateTo string
---@field responseCode? number
---@field responseMessage? string
---@field txCount? number
---@field txIdEnd? string
---@field txIdStart? string
---@field txSeqNoEnd? number
---@field txSeqNoStart? number
---@field txTotal? number

---@class EcDataEcom
---@field ecomData? string
---@field responseCode? number
---@field responseMessage? string
---@field terminalId number
---@field transactionId string
---@field transactionType string

---@class EcDataEcomCreateData
---@field ecomData? string
---@field responseCode? number
---@field responseMessage? string
---@field terminalId number
---@field transactionId string
---@field transactionType string

---@class EcomParameter
---@field ecomPass? string
---@field ecomSkey? string
---@field responseCode? number
---@field responseMessage? string
---@field terminalId number

---@class EcomParameterCreateData
---@field ecomPass? string
---@field ecomSkey? string
---@field responseCode? number
---@field responseMessage? string
---@field terminalId number

---@class EcrData
---@field ecrData? string
---@field responseCode? number
---@field responseMessage? string
---@field terminalId number
---@field transactionId string
---@field transactionType string

---@class EcrDataCreateData
---@field ecrData? string
---@field responseCode? number
---@field responseMessage? string
---@field terminalId number
---@field transactionId string
---@field transactionType string

---@class EmvData
---@field emvData? string
---@field responseCode? number
---@field responseMessage? string
---@field terminalId number
---@field transactionId string
---@field transactionType string

---@class EmvDataCreateData
---@field emvData? string
---@field responseCode? number
---@field responseMessage? string
---@field terminalId number
---@field transactionId string
---@field transactionType string

---@class EnableAcquiring
---@field accountNo? number
---@field additionalData? table
---@field corporateUuid string
---@field currency string
---@field merchantCategoryCode number
---@field packageOrderUuid string
---@field productOrderUuid string
---@field responseCode? number
---@field responseMessage? string
---@field sortingCode? number
---@field templateName string
---@field terminalIdAcq? string
---@field terminalIds? table
---@field vuNummer? string

---@class EnableAcquiringCreateData
---@field accountNo? number
---@field additionalData? table
---@field corporateUuid string
---@field currency string
---@field merchantCategoryCode number
---@field packageOrderUuid string
---@field productOrderUuid string
---@field responseCode? number
---@field responseMessage? string
---@field sortingCode? number
---@field templateName string
---@field terminalIdAcq? string
---@field terminalIds? table
---@field vuNummer? string

---@class GetMerchantContractNumber
---@field merchantContractNumber string
---@field responseCode? number
---@field responseMessage? string

---@class GetMerchantContractNumberCreateData
---@field merchantContractNumber string
---@field responseCode? number
---@field responseMessage? string

---@class GetTemplateXml
---@field responseCode? number
---@field responseMessage? string
---@field templateName string

---@class GetTemplateXmlCreateData
---@field responseCode? number
---@field responseMessage? string
---@field templateName string

---@class IntroduceMandator
---@field mandatorName string
---@field responseCode? number
---@field responseMessage? string

---@class IntroduceMandatorCreateData
---@field mandatorName string
---@field responseCode? number
---@field responseMessage? string

---@class IntroducePackage
---@field responseCode? number
---@field responseMessage? string
---@field terminalTemplateDescription string

---@class IntroducePackageCreateData
---@field responseCode? number
---@field responseMessage? string
---@field terminalTemplateDescription string

---@class KeepAlive
---@field hwserialno? string
---@field kaDateTimeFrom? string
---@field kaDateTimeTo? string
---@field keepAliveData? table
---@field pagination? table
---@field responseCode? number
---@field responseMessage? string
---@field terminalDateTimeFrom? string
---@field terminalDateTimeTo? string
---@field terminalId? number

---@class KeepAliveCreateData
---@field hwserialno? string
---@field kaDateTimeFrom? string
---@field kaDateTimeTo? string
---@field keepAliveData? table
---@field pagination? table
---@field responseCode? number
---@field responseMessage? string
---@field terminalDateTimeFrom? string
---@field terminalDateTimeTo? string
---@field terminalId? number

---@class ListTerminal
---@field corporateUuid? table
---@field filter? table
---@field pagination? table
---@field responseCode? number
---@field responseMessage? string
---@field terminals? table

---@class ListTerminalCreateData
---@field corporateUuid? table
---@field filter? table
---@field pagination? table
---@field responseCode? number
---@field responseMessage? string
---@field terminals? table

---@class MandatorClearingExport
---@field clearingDateFrom string
---@field clearingDateTo string
---@field pagination? table
---@field records? table
---@field responseCode? number
---@field responseMessage? string

---@class MandatorClearingExportCreateData
---@field clearingDateFrom string
---@field clearingDateTo string
---@field pagination? table
---@field records? table
---@field responseCode? number
---@field responseMessage? string

---@class MandatorClearingExportDownload
---@field clearingDateFrom string
---@field clearingDateTo string
---@field fileId? string
---@field filenameTemplate? string
---@field id? string
---@field responseCode? number
---@field responseMessage? string
---@field status? string

---@class MandatorClearingExportDownloadLoadMatch
---@field id string

---@class MandatorClearingExportDownloadCreateData
---@field clearingDateFrom string
---@field clearingDateTo string
---@field fileId? string
---@field filenameTemplate? string
---@field id? string
---@field responseCode? number
---@field responseMessage? string
---@field status? string

---@class MandatorClearingExportSummary
---@field clearingDateFrom string
---@field clearingDateTo string
---@field records? table
---@field responseCode? number
---@field responseMessage? string

---@class MandatorClearingExportSummaryCreateData
---@field clearingDateFrom string
---@field clearingDateTo string
---@field records? table
---@field responseCode? number
---@field responseMessage? string

---@class MerchantPortalServicesApi
---@field ["3DSecure"]? string
---@field authorizationCode? string
---@field cardBrand? string
---@field clearingAmountFrom? string
---@field clearingAmountTo? string
---@field clearingCurrency? string
---@field clearingStatus? string
---@field corporateUUID? string
---@field orderByTransactionDate? string
---@field pagination? table
---@field receiptNumber? string
---@field referencedTransactionId? string
---@field retrievalReferenceNumber? string
---@field sourceId? number
---@field tecsengineResponseCodeFrom? string
---@field tecsengineResponseCodeTo? string
---@field terminalId? number
---@field traceNumber? string
---@field transactionAmountFrom? string
---@field transactionAmountTo? string
---@field transactionDateFrom? string
---@field transactionDateTo? string
---@field transactionId? string
---@field transactionType? string
---@field wallet? string

---@class MerchantPortalServicesApiCreateData
---@field ["3DSecure"]? string
---@field authorizationCode? string
---@field cardBrand? string
---@field clearingAmountFrom? string
---@field clearingAmountTo? string
---@field clearingCurrency? string
---@field clearingStatus? string
---@field corporateUUID? string
---@field orderByTransactionDate? string
---@field pagination? table
---@field receiptNumber? string
---@field referencedTransactionId? string
---@field retrievalReferenceNumber? string
---@field sourceId? number
---@field tecsengineResponseCodeFrom? string
---@field tecsengineResponseCodeTo? string
---@field terminalId? number
---@field traceNumber? string
---@field transactionAmountFrom? string
---@field transactionAmountTo? string
---@field transactionDateFrom? string
---@field transactionDateTo? string
---@field transactionId? string
---@field transactionType? string
---@field wallet? string

---@class MoveTid
---@field productorderuuids table
---@field responseCode? number
---@field responseMessage? string
---@field targetPackageorderuuid? string
---@field targetProductorderuuid? string

---@class MoveTidCreateData
---@field productorderuuids table
---@field responseCode? number
---@field responseMessage? string
---@field targetPackageorderuuid? string
---@field targetProductorderuuid? string

---@class PaymentManual
---@field acquirerName? string
---@field amount number
---@field authorizationNumber? string
---@field cardNumber string
---@field cardType? string
---@field currency string
---@field cvc? string
---@field dateTimeTx? string
---@field expDate string
---@field merchantId? string
---@field originalTransactionId? string
---@field password? string
---@field responseCode? string
---@field responseMessage? string
---@field terminalId? string
---@field transactionId? string
---@field txtype string

---@class PaymentManualCreateData
---@field acquirerName? string
---@field amount number
---@field authorizationNumber? string
---@field cardNumber string
---@field cardType? string
---@field currency string
---@field cvc? string
---@field dateTimeTx? string
---@field expDate string
---@field merchantId? string
---@field originalTransactionId? string
---@field password? string
---@field responseCode? string
---@field responseMessage? string
---@field terminalId? string
---@field transactionId? string
---@field txtype string

---@class PaymentSred
---@field amount number
---@field currency string
---@field device? string
---@field devicePayload string
---@field expDate? string
---@field mode? string
---@field panMasked? string
---@field password? string
---@field serial? string
---@field serviceCode? string
---@field terminalId string
---@field txtype string

---@class PaymentSredCreateData
---@field amount number
---@field currency string
---@field device? string
---@field devicePayload string
---@field expDate? string
---@field mode? string
---@field panMasked? string
---@field password? string
---@field serial? string
---@field serviceCode? string
---@field terminalId string
---@field txtype string

---@class PreAuthTransactionCompletion
---@field acquirerId? string
---@field acquirerName? string
---@field actualBonusPoints? string
---@field amount? number
---@field authorizationCode? string
---@field balanceAmount? string
---@field cardBrand? string
---@field cardNumber? string
---@field cardNumberReference string
---@field clientId number
---@field currency string
---@field cvc? string
---@field ecData? string
---@field ecrData? string
---@field emvData? string
---@field exchangeFee? number
---@field exchangeRate? string
---@field languageCode? string
---@field merchantAddress? string
---@field merchantName? string
---@field merchantNumber? string
---@field messageType? string
---@field originalTraceNumber? number
---@field originalTransactionId? string
---@field password? string
---@field paymentReason? string
---@field receiptFooter? string
---@field receiptHeader? string
---@field receiptLayout? number
---@field receiptNumber string
---@field responseCode? number
---@field responseMessage? string
---@field serialNumber? string
---@field svc? string
---@field terminalId number
---@field terminalLocation? string
---@field traceNumber? number
---@field transactionDate? string
---@field transactionId? string
---@field transactionType string
---@field txType? string
---@field userData? string

---@class PreAuthTransactionCompletionCreateData
---@field acquirerId? string
---@field acquirerName? string
---@field actualBonusPoints? string
---@field amount? number
---@field authorizationCode? string
---@field balanceAmount? string
---@field cardBrand? string
---@field cardNumber? string
---@field cardNumberReference string
---@field clientId number
---@field currency string
---@field cvc? string
---@field ecData? string
---@field ecrData? string
---@field emvData? string
---@field exchangeFee? number
---@field exchangeRate? string
---@field languageCode? string
---@field merchantAddress? string
---@field merchantName? string
---@field merchantNumber? string
---@field messageType? string
---@field originalTraceNumber? number
---@field originalTransactionId? string
---@field password? string
---@field paymentReason? string
---@field receiptFooter? string
---@field receiptHeader? string
---@field receiptLayout? number
---@field receiptNumber string
---@field responseCode? number
---@field responseMessage? string
---@field serialNumber? string
---@field svc? string
---@field terminalId number
---@field terminalLocation? string
---@field traceNumber? number
---@field transactionDate? string
---@field transactionId? string
---@field transactionType string
---@field txType? string
---@field userData? string

---@class ReactivateTerminal
---@field corporateUuid? string
---@field packageOrderUuid? string
---@field productOrderUuid? string
---@field reactivationReason string
---@field responseCode? number
---@field responseMessage? string
---@field terminalId number

---@class ReactivateTerminalCreateData
---@field corporateUuid? string
---@field packageOrderUuid? string
---@field productOrderUuid? string
---@field reactivationReason string
---@field responseCode? number
---@field responseMessage? string
---@field terminalId number

---@class RefundTransaction
---@field acquirerId? string
---@field acquirerName? string
---@field actualBonusPoints? string
---@field amount? number
---@field authorizationCode? string
---@field balanceAmount? string
---@field cardBrand? string
---@field cardNumber? string
---@field clientId number
---@field currency string
---@field cvc? string
---@field ecData? string
---@field ecrData? string
---@field emvData? string
---@field exchangeFee? number
---@field exchangeRate? string
---@field languageCode? string
---@field merchantAddress? string
---@field merchantName? string
---@field merchantNumber? string
---@field messageType? string
---@field originalTraceNumber? number
---@field originalTransactionId? string
---@field password? string
---@field paymentReason? string
---@field receiptFooter? string
---@field receiptHeader? string
---@field receiptLayout? number
---@field receiptNumber string
---@field responseCode? number
---@field responseMessage? string
---@field serialNumber? string
---@field svc? string
---@field terminalId number
---@field terminalLocation? string
---@field traceNumber? number
---@field transactionDate? string
---@field transactionId? string
---@field txType? string
---@field userData? string

---@class RefundTransactionCreateData
---@field acquirerId? string
---@field acquirerName? string
---@field actualBonusPoints? string
---@field amount? number
---@field authorizationCode? string
---@field balanceAmount? string
---@field cardBrand? string
---@field cardNumber? string
---@field clientId number
---@field currency string
---@field cvc? string
---@field ecData? string
---@field ecrData? string
---@field emvData? string
---@field exchangeFee? number
---@field exchangeRate? string
---@field languageCode? string
---@field merchantAddress? string
---@field merchantName? string
---@field merchantNumber? string
---@field messageType? string
---@field originalTraceNumber? number
---@field originalTransactionId? string
---@field password? string
---@field paymentReason? string
---@field receiptFooter? string
---@field receiptHeader? string
---@field receiptLayout? number
---@field receiptNumber string
---@field responseCode? number
---@field responseMessage? string
---@field serialNumber? string
---@field svc? string
---@field terminalId number
---@field terminalLocation? string
---@field traceNumber? number
---@field transactionDate? string
---@field transactionId? string
---@field txType? string
---@field userData? string

---@class RegisterTecsCompany
---@field corporateUuid string
---@field packageOrderUuid string
---@field partnerId? number
---@field partnerName? string
---@field productOrderUuid string
---@field responseCode? number
---@field responseMessage? string
---@field templateName string

---@class RegisterTecsCompanyCreateData
---@field corporateUuid string
---@field packageOrderUuid string
---@field partnerId? number
---@field partnerName? string
---@field productOrderUuid string
---@field responseCode? number
---@field responseMessage? string
---@field templateName string

---@class RegisterTerminal
---@field additionalData? table
---@field corporateUuid string
---@field packageOrderUuid string
---@field productOrderUuid string
---@field responseCode? number
---@field responseMessage? string
---@field tecsWebSecretKey? string
---@field templateName string
---@field terminalCountryCode string
---@field terminalId? number
---@field terminalIdAcq? string
---@field terminalLanguageCode string
---@field terminalLocation string
---@field terminalSerialNumber? string
---@field tokenIOAlias? string
---@field tokenIOIban? string
---@field tokenIOMemberId? string
---@field webShopUrl? string

---@class RegisterTerminalCreateData
---@field additionalData? table
---@field corporateUuid string
---@field packageOrderUuid string
---@field productOrderUuid string
---@field responseCode? number
---@field responseMessage? string
---@field tecsWebSecretKey? string
---@field templateName string
---@field terminalCountryCode string
---@field terminalId? number
---@field terminalIdAcq? string
---@field terminalLanguageCode string
---@field terminalLocation string
---@field terminalSerialNumber? string
---@field tokenIOAlias? string
---@field tokenIOIban? string
---@field tokenIOMemberId? string
---@field webShopUrl? string

---@class ReportData
---@field cardBrandReportData? table
---@field clearingDateFrom string
---@field clearingDateTo string
---@field corporateId string
---@field currency string
---@field responseCode? number
---@field responseMessage? string
---@field sumOverCreditTx? table
---@field sumOverDebitTx? table
---@field terminalId? number

---@class ReportDataCreateData
---@field cardBrandReportData? table
---@field clearingDateFrom string
---@field clearingDateTo string
---@field corporateId string
---@field currency string
---@field responseCode? number
---@field responseMessage? string
---@field sumOverCreditTx? table
---@field sumOverDebitTx? table
---@field terminalId? number

---@class StatusTransaction
---@field acquirerName? string
---@field acquirerTerminalId? string
---@field amount? number
---@field applicationCryptogram? string
---@field authorizationCode? string|nil
---@field authorizationDate? string
---@field cardBrand? string
---@field cardEntry? string
---@field cardExpiration? string
---@field cardNumber? string
---@field clearingAmount? number
---@field clearingBatchId? string
---@field clearingCurrency? string
---@field clearingDate? string
---@field clearingProcessedDate? string
---@field clearingStatus? string
---@field clientId? number
---@field currency? string
---@field cvm? string
---@field ecrData? string
---@field emvApplicationId? string
---@field emvApplicationLabel? string
---@field merchantName? string
---@field merchantNumber? string
---@field originalClientId? string
---@field originalTerminalId? number
---@field originalTransactionId? string
---@field paymentReason? string
---@field receiptNumber? string
---@field responseCode? number
---@field responseCodeFromAS? string
---@field responseMessage? string
---@field retrievalReferenceNumber? string
---@field serviceCode? string
---@field settlementStatus? string
---@field sourceId? number
---@field tecsengineResponseCode? number
---@field tecsengineResponseText? string
---@field terminalEndOfDayDate? string
---@field terminalId? number
---@field terminalLocation? string
---@field tipAmount? number
---@field traceNumber? number
---@field transactionClearingDate? string
---@field transactionDate? string
---@field transactionId? string
---@field transactionSeqNumber? number
---@field transactionServerDate? string
---@field transactionSource? string
---@field transactionType? string

---@class StatusTransactionCreateData
---@field acquirerName? string
---@field acquirerTerminalId? string
---@field amount? number
---@field applicationCryptogram? string
---@field authorizationCode? string|nil
---@field authorizationDate? string
---@field cardBrand? string
---@field cardEntry? string
---@field cardExpiration? string
---@field cardNumber? string
---@field clearingAmount? number
---@field clearingBatchId? string
---@field clearingCurrency? string
---@field clearingDate? string
---@field clearingProcessedDate? string
---@field clearingStatus? string
---@field clientId? number
---@field currency? string
---@field cvm? string
---@field ecrData? string
---@field emvApplicationId? string
---@field emvApplicationLabel? string
---@field merchantName? string
---@field merchantNumber? string
---@field originalClientId? string
---@field originalTerminalId? number
---@field originalTransactionId? string
---@field paymentReason? string
---@field receiptNumber? string
---@field responseCode? number
---@field responseCodeFromAS? string
---@field responseMessage? string
---@field retrievalReferenceNumber? string
---@field serviceCode? string
---@field settlementStatus? string
---@field sourceId? number
---@field tecsengineResponseCode? number
---@field tecsengineResponseText? string
---@field terminalEndOfDayDate? string
---@field terminalId? number
---@field terminalLocation? string
---@field tipAmount? number
---@field traceNumber? number
---@field transactionClearingDate? string
---@field transactionDate? string
---@field transactionId? string
---@field transactionSeqNumber? number
---@field transactionServerDate? string
---@field transactionSource? string
---@field transactionType? string

---@class StoreTerminalParameter
---@field acqTabNexo? table
---@field configVersion? string
---@field responseCode? number
---@field responseMessage? string
---@field serialNumber string
---@field tidSent? string

---@class StoreTerminalParameterCreateData
---@field acqTabNexo? table
---@field configVersion? string
---@field responseCode? number
---@field responseMessage? string
---@field serialNumber string
---@field tidSent? string

---@class TerminalId
---@field deviceSerialNumber table
---@field duplicateTerminalIds? table
---@field responseCode? number
---@field responseMessage? string
---@field terminals? table

---@class TerminalIdCreateData
---@field deviceSerialNumber table
---@field duplicateTerminalIds? table
---@field responseCode? number
---@field responseMessage? string
---@field terminals? table

---@class TransactionHistory
---@field ["3DSecure"]? string
---@field authorizationCode? string
---@field cardBrand? string
---@field clearingAmountFrom? string
---@field clearingAmountTo? string
---@field clearingCurrency? string
---@field clearingStatus? string
---@field corporateUUID? string
---@field orderByTransactionDate? string
---@field pagination? table
---@field paymentTokenPublicId? string
---@field receiptNumber? string
---@field referencedTransactionId? string
---@field responseCode? number
---@field responseMessage? string
---@field retrievalReferenceNumber? string
---@field sourceId? number
---@field tecsengineResponseCodeFrom? string
---@field tecsengineResponseCodeTo? string
---@field terminalId? number
---@field traceNumber? string
---@field transactionAmountFrom? string
---@field transactionAmountTo? string
---@field transactionDateFrom? string
---@field transactionDateTo? string
---@field transactionHistories? table
---@field transactionId? string
---@field transactionType? string
---@field wallet? string

---@class TransactionHistoryCreateData
---@field ["3DSecure"]? string
---@field authorizationCode? string
---@field cardBrand? string
---@field clearingAmountFrom? string
---@field clearingAmountTo? string
---@field clearingCurrency? string
---@field clearingStatus? string
---@field corporateUUID? string
---@field orderByTransactionDate? string
---@field pagination? table
---@field paymentTokenPublicId? string
---@field receiptNumber? string
---@field referencedTransactionId? string
---@field responseCode? number
---@field responseMessage? string
---@field retrievalReferenceNumber? string
---@field sourceId? number
---@field tecsengineResponseCodeFrom? string
---@field tecsengineResponseCodeTo? string
---@field terminalId? number
---@field traceNumber? string
---@field transactionAmountFrom? string
---@field transactionAmountTo? string
---@field transactionDateFrom? string
---@field transactionDateTo? string
---@field transactionHistories? table
---@field transactionId? string
---@field transactionType? string
---@field wallet? string

---@class TransactionsCount
---@field period? string
---@field responseCode? number
---@field responseMessage? string
---@field transactionDateFrom? string
---@field transactionDateTo? string
---@field transactionsCount? table

---@class TransactionsCountCreateData
---@field period? string
---@field responseCode? number
---@field responseMessage? string
---@field transactionDateFrom? string
---@field transactionDateTo? string
---@field transactionsCount? table

---@class TransactionsCountCardBrand
---@field period? string
---@field responseCode? number
---@field responseMessage? string
---@field transactionDateFrom? string
---@field transactionDateTo? string
---@field transactionsCount? table

---@class TransactionsCountCardBrandCreateData
---@field period? string
---@field responseCode? number
---@field responseMessage? string
---@field transactionDateFrom? string
---@field transactionDateTo? string
---@field transactionsCount? table

---@class TransactionsTurnover
---@field period? string
---@field responseCode? number
---@field responseMessage? string
---@field transactionDateFrom? string
---@field transactionDateTo? string
---@field turnovers? table

---@class TransactionsTurnoverCreateData
---@field period? string
---@field responseCode? number
---@field responseMessage? string
---@field transactionDateFrom? string
---@field transactionDateTo? string
---@field turnovers? table

---@class UpdateMerchant
---@field city? string
---@field corporateUuid string
---@field country? string
---@field merchantCategoryCode? string
---@field name? string
---@field responseCode? number
---@field responseMessage? string
---@field state? string
---@field street? string
---@field vuNummer? string
---@field zipcode? string

---@class UpdateMerchantCreateData
---@field city? string
---@field corporateUuid string
---@field country? string
---@field merchantCategoryCode? string
---@field name? string
---@field responseCode? number
---@field responseMessage? string
---@field state? string
---@field street? string
---@field vuNummer? string
---@field zipcode? string

---@class UpdateTemplateXml
---@field responseCode? number
---@field responseMessage? string
---@field templateName string
---@field templateXml string

---@class UpdateTemplateXmlCreateData
---@field responseCode? number
---@field responseMessage? string
---@field templateName string
---@field templateXml string

---@class Version
---@field appName? string
---@field buildDate? string
---@field version? string

---@class VersionLoadMatch
---@field appName? string
---@field buildDate? string
---@field version? string

local M = {}

return M
