// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(4,
      "name", v_str("BluefinTecsMerchantServices"),
      "slug", v_str("bluefin-tecs-merchant-services"),
      "version", v_str("0.0.1"),
      "target", v_str("c")),
    "feature", cmap(1,
      "test", cmap(1,
        "options", cmap(1,
          "active", v_bool(false)))),
    "options", cmap(4,
      "base", v_str("https://test.tecs.at/merchantservices"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(39,
        "cancel_transaction", v_map(),
        "check_card_black_listed", v_map(),
        "create_product", v_map(),
        "deactivate_terminal", v_map(),
        "digital_services_api", v_map(),
        "ec_data_ecom", v_map(),
        "ecom_parameter", v_map(),
        "ecr_data", v_map(),
        "emv_data", v_map(),
        "enable_acquiring", v_map(),
        "get_merchant_contract_number", v_map(),
        "get_template_xml", v_map(),
        "introduce_mandator", v_map(),
        "introduce_package", v_map(),
        "keep_alive", v_map(),
        "list_terminal", v_map(),
        "mandator_clearing_export", v_map(),
        "mandator_clearing_export_download", v_map(),
        "mandator_clearing_export_summary", v_map(),
        "merchant_portal_services_api", v_map(),
        "move_tid", v_map(),
        "payment_manual", v_map(),
        "payment_sred", v_map(),
        "pre_auth_transaction_completion", v_map(),
        "reactivate_terminal", v_map(),
        "refund_transaction", v_map(),
        "register_tecs_company", v_map(),
        "register_terminal", v_map(),
        "report_data", v_map(),
        "status_transaction", v_map(),
        "store_terminal_parameter", v_map(),
        "terminal_id", v_map(),
        "transaction_history", v_map(),
        "transactions_count", v_map(),
        "transactions_count_card_brand", v_map(),
        "transactions_turnover", v_map(),
        "update_merchant", v_map(),
        "update_template_xml", v_map(),
        "version", v_map()),
      "auth", cmap(1,
        "prefix", v_str("Bearer"))),
    "entity", cmap(39,
      "cancel_transaction", cmap(4,
        "fields", clist(40,
          cmap(2,
            "name", v_str("acquirerId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("acquirerName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("actualBonusPoints"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("amount"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$INTEGER`"))),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("authorizationCode"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("balanceAmount"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("cardBrand"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("cardNumber"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("clientId"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("currency"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("cvc"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("ecData"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("ecrData"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("emvData"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("exchangeFee"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("exchangeRate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("languageCode"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("merchantAddress"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("merchantName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("merchantNumber"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("messageType"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("originalTraceNumber"),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("originalTransactionId"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("password"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("paymentReason"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("receiptFooter"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("receiptHeader"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("receiptLayout"),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("receiptNumber"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("serialNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("svc"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminalId"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("terminalLocation"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("traceNumber"),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("transactionDate"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("transactionId"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("txType"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("userData"),
            "type", v_str("`$STRING`"))),
        "name", v_str("cancel_transaction"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/cancelTransaction"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("cancelTransaction")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "check_card_black_listed", cmap(4,
        "fields", clist(3,
          cmap(2,
            "name", v_str("cardNo"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`"))),
        "name", v_str("check_card_black_listed"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/checkCardBlackListed"),
                "parts", clist(1,
                  v_str("checkCardBlackListed")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "create_product", cmap(4,
        "fields", clist(7,
          cmap(2,
            "name", v_str("acquirerId"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("templateName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("templateType"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("templateXml"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminalType"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("create_product"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/createProduct"),
                "parts", clist(1,
                  v_str("createProduct")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "deactivate_terminal", cmap(4,
        "fields", clist(7,
          cmap(2,
            "name", v_str("corporateUuid"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("deactivationReason"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("packageOrderUuid"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("productOrderUuid"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminalId"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("deactivate_terminal"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/deactivateTerminal"),
                "parts", clist(1,
                  v_str("deactivateTerminal")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "digital_services_api", cmap(4,
        "fields", clist(10,
          cmap(4,
            "name", v_str("clearingDateFrom"),
            "req", v_bool(true),
            "short", v_str("Date and time in the format yyyy-MM-dd'T'HH:mm:ssz"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("clearingDateTo"),
            "req", v_bool(true),
            "short", v_str("Date and time in the format yyyy-MM-dd'T'HH:mm:ssz"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("txCount"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("txIdEnd"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("txIdStart"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("txSeqNoEnd"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("txSeqNoStart"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("txTotal"),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("digital_services_api"),
        "op", cmap(2,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(8,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("file_id"),
                      "orig", v_str("file_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/digitalservices/mandatorClearingExportDownload/{fileId}"),
                "parts", clist(4,
                  v_str("public"),
                  v_str("digitalservices"),
                  v_str("mandatorClearingExportDownload"),
                  v_str("{file_id}")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "fileId", v_str("file_id"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("file_id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/digitalservices/mandatorClearingExportMetadata"),
                "parts", clist(3,
                  v_str("public"),
                  v_str("digitalservices"),
                  v_str("mandatorClearingExportMetadata")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/public/digitalservices/mandatorClearingExportDownload/status"),
                "parts", clist(4,
                  v_str("public"),
                  v_str("digitalservices"),
                  v_str("mandatorClearingExportDownload"),
                  v_str("status")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", clist(1,
            clist(1,
              v_str("mandator_clearing_export_download"))))),
      "ec_data_ecom", cmap(4,
        "fields", clist(6,
          cmap(2,
            "name", v_str("ecomData"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminalId"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("transactionId"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("transactionType"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("ec_data_ecom"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/getEcData"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("getEcData")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "ecom_parameter", cmap(4,
        "fields", clist(5,
          cmap(2,
            "name", v_str("ecomPass"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("ecomSkey"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminalId"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("ecom_parameter"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/getEcomParameters"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("getEcomParameters")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "ecr_data", cmap(4,
        "fields", clist(6,
          cmap(2,
            "name", v_str("ecrData"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminalId"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("transactionId"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("transactionType"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("ecr_data"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/getEcrData"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("getEcrData")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "emv_data", cmap(4,
        "fields", clist(6,
          cmap(2,
            "name", v_str("emvData"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminalId"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("transactionId"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("transactionType"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("emv_data"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/getEmvData"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("getEmvData")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "enable_acquiring", cmap(4,
        "fields", clist(14,
          cmap(2,
            "name", v_str("accountNo"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("additionalData"),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("corporateUuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("currency"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("merchantCategoryCode"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("packageOrderUuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("productOrderUuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("sortingCode"),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("templateName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("terminalIdAcq"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("terminalIds"),
            "type", v_str("`$ARRAY`")),
          cmap(2,
            "name", v_str("vuNummer"),
            "type", v_str("`$STRING`"))),
        "name", v_str("enable_acquiring"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/enableAcquiring"),
                "parts", clist(1,
                  v_str("enableAcquiring")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "get_merchant_contract_number", cmap(4,
        "fields", clist(3,
          cmap(3,
            "name", v_str("merchantContractNumber"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`"))),
        "name", v_str("get_merchant_contract_number"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/getMerchantContractNumber"),
                "parts", clist(1,
                  v_str("getMerchantContractNumber")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "get_template_xml", cmap(4,
        "fields", clist(3,
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("templateName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("get_template_xml"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/getTemplateXml"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("getTemplateXml")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "introduce_mandator", cmap(4,
        "fields", clist(3,
          cmap(3,
            "name", v_str("mandatorName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`"))),
        "name", v_str("introduce_mandator"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/introduceMandator"),
                "parts", clist(1,
                  v_str("introduceMandator")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "introduce_package", cmap(4,
        "fields", clist(3,
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminalTemplateDescription"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("introduce_package"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/introducePackage"),
                "parts", clist(1,
                  v_str("introducePackage")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "keep_alive", cmap(4,
        "fields", clist(10,
          cmap(2,
            "name", v_str("hwserialno"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("kaDateTimeFrom"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("kaDateTimeTo"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("keepAliveData"),
            "type", v_str("`$ARRAY`")),
          cmap(2,
            "name", v_str("pagination"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("terminalDateTimeFrom"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("terminalDateTimeTo"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("terminalId"),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("keep_alive"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/keepalive"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("keepalive")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "list_terminal", cmap(4,
        "fields", clist(6,
          cmap(2,
            "name", v_str("corporateUuid"),
            "type", v_str("`$ARRAY`")),
          cmap(2,
            "name", v_str("filter"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("pagination"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("terminals"),
            "type", v_str("`$ARRAY`"))),
        "name", v_str("list_terminal"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/listTerminals"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("listTerminals")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "mandator_clearing_export", cmap(4,
        "fields", clist(6,
          cmap(4,
            "name", v_str("clearingDateFrom"),
            "req", v_bool(true),
            "short", v_str("Date and time in the format yyyy-MM-dd'T'HH:mm:ssZ"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("clearingDateTo"),
            "req", v_bool(true),
            "short", v_str("Date and time in the format yyyy-MM-dd'T'HH:mm:ssZ"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("pagination"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("records"),
            "type", v_str("`$ARRAY`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`"))),
        "name", v_str("mandator_clearing_export"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/digitalservices/mandatorClearingExport"),
                "parts", clist(3,
                  v_str("public"),
                  v_str("digitalservices"),
                  v_str("mandatorClearingExport")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "mandator_clearing_export_download", cmap(4,
        "fields", clist(7,
          cmap(4,
            "name", v_str("clearingDateFrom"),
            "req", v_bool(true),
            "short", v_str("Start date for clearing export (inclusive)"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("clearingDateTo"),
            "req", v_bool(true),
            "short", v_str("End date for clearing export (inclusive)"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("fileId"),
            "short", v_str("Unique file identifier for tracking and downloading"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("filenameTemplate"),
            "short", v_str("Optional filename template for the export file"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("status"),
            "short", v_str("Processing status of the export request"),
            "type", v_str("`$STRING`"))),
        "name", v_str("mandator_clearing_export_download"),
        "op", cmap(2,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/digitalservices/mandatorClearingExportDownload"),
                "parts", clist(3,
                  v_str("public"),
                  v_str("digitalservices"),
                  v_str("mandatorClearingExportDownload")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("file_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/public/digitalservices/mandatorClearingExportDownload/{fileId}"),
                "parts", clist(4,
                  v_str("public"),
                  v_str("digitalservices"),
                  v_str("mandatorClearingExportDownload"),
                  v_str("{id}")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "fileId", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "mandator_clearing_export_summary", cmap(4,
        "fields", clist(5,
          cmap(4,
            "name", v_str("clearingDateFrom"),
            "req", v_bool(true),
            "short", v_str("Date and time in the format yyyy-MM-dd'T'HH:mm:ssz"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("clearingDateTo"),
            "req", v_bool(true),
            "short", v_str("Date and time in the format yyyy-MM-dd'T'HH:mm:ssz"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("records"),
            "type", v_str("`$ARRAY`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`"))),
        "name", v_str("mandator_clearing_export_summary"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/digitalservices/mandatorClearingExportSummary"),
                "parts", clist(3,
                  v_str("public"),
                  v_str("digitalservices"),
                  v_str("mandatorClearingExportSummary")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_services_api", cmap(4,
        "fields", clist(25,
          cmap(2,
            "name", v_str("3DSecure"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("authorizationCode"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("cardBrand"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("clearingAmountFrom"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("clearingAmountTo"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("clearingCurrency"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("clearingStatus"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("corporateUUID"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("orderByTransactionDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("pagination"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("receiptNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("referencedTransactionId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("retrievalReferenceNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("sourceId"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("tecsengineResponseCodeFrom"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("tecsengineResponseCodeTo"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("terminalId"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("traceNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionAmountFrom"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionAmountTo"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionDateFrom"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionDateTo"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionType"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("wallet"),
            "short", v_str("Filter by wallet type."),
            "type", v_str("`$STRING`"))),
        "name", v_str("merchant_portal_services_api"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/transactionHistoryCsv"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("transactionHistoryCsv")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "move_tid", cmap(4,
        "fields", clist(5,
          cmap(3,
            "name", v_str("productorderuuids"),
            "req", v_bool(true),
            "type", v_str("`$ARRAY`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("targetPackageorderuuid"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("targetProductorderuuid"),
            "type", v_str("`$STRING`"))),
        "name", v_str("move_tid"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/moveTid"),
                "parts", clist(1,
                  v_str("moveTid")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "payment_manual", cmap(4,
        "fields", clist(17,
          cmap(3,
            "name", v_str("acquirerName"),
            "short", v_str("Acquirer name parsed from KKG field"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("amount"),
            "req", v_bool(true),
            "short", v_str("Transaction amount in minor units (cents)"),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("authorizationNumber"),
            "short", v_str("Authorization number from the gateway"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("cardNumber"),
            "req", v_bool(true),
            "short", v_str("Card number - 12 to 19 digits, must pass Luhn validation"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("cardType"),
            "short", v_str("Card type parsed from KKG field"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("currency"),
            "req", v_bool(true),
            "short", v_str("Currency code - 3 uppercase letters (ISO 4217)"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("cvc"),
            "short", v_str("Card verification code - 3-4 digits (optional)"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("dateTimeTx"),
            "short", v_str("Date and time of the transaction"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("expDate"),
            "req", v_bool(true),
            "short", v_str("Card expiry date in MMYY format"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("merchantId"),
            "short", v_str("Merchant ID (VU-NUMMER)"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("originalTransactionId"),
            "short", v_str("Original transaction ID from gateway"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("password"),
            "short", v_str("Terminal password sent as Kennwort in TECS XML (optional)"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("responseCode"),
            "short", v_str("Response code - 00 for success, otherwise error code"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("responseMessage"),
            "short", v_str("Response message - 'Approved' for success, error description otherwise"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("terminalId"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "short", v_str("Terminal ID used for the transaction"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("transactionId"),
            "short", v_str("Transaction ID generated by the backend"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("txtype"),
            "req", v_bool(true),
            "short", v_str("Transaction type"),
            "type", v_str("`$STRING`"))),
        "name", v_str("payment_manual"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/paymentManual"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("paymentManual")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "payment_sred", cmap(4,
        "fields", clist(12,
          cmap(4,
            "name", v_str("amount"),
            "req", v_bool(true),
            "short", v_str("Transaction amount in minor units (cents)"),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "name", v_str("currency"),
            "req", v_bool(true),
            "short", v_str("Currency code - 3 uppercase letters (ISO 4217)"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("device"),
            "short", v_str("Device type that provided the SRED payload"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("devicePayload"),
            "req", v_bool(true),
            "short", v_str("SRED encrypted device payload from the device (minimum 32 characters)"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("expDate"),
            "short", v_str("Card expiry date in MMYY format"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("mode"),
            "short", v_str("Decryption mode"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("panMasked"),
            "short", v_str("Masked PAN (first 6 and last 4 digits)"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("password"),
            "short", v_str("Terminal password sent as Kennwort in TECS XML (optional)"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("serial"),
            "short", v_str("Device serial number"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("serviceCode"),
            "short", v_str("Service code from the card"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("terminalId"),
            "req", v_bool(true),
            "short", v_str("Terminal ID - 8 digits"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("txtype"),
            "req", v_bool(true),
            "short", v_str("Transaction type"),
            "type", v_str("`$STRING`"))),
        "name", v_str("payment_sred"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/paymentSred"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("paymentSred")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "pre_auth_transaction_completion", cmap(4,
        "fields", clist(42,
          cmap(2,
            "name", v_str("acquirerId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("acquirerName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("actualBonusPoints"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("amount"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$INTEGER`"))),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("authorizationCode"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("balanceAmount"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("cardBrand"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("cardNumber"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("cardNumberReference"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("clientId"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("currency"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("cvc"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("ecData"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("ecrData"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("emvData"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("exchangeFee"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("exchangeRate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("languageCode"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("merchantAddress"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("merchantName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("merchantNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("messageType"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("originalTraceNumber"),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("originalTransactionId"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("password"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("paymentReason"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("receiptFooter"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("receiptHeader"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("receiptLayout"),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("receiptNumber"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("serialNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("svc"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminalId"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("terminalLocation"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("traceNumber"),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("transactionDate"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("transactionId"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("transactionType"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("txType"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("userData"),
            "type", v_str("`$STRING`"))),
        "name", v_str("pre_auth_transaction_completion"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/paymentTransaction"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("paymentTransaction")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/preAuthCompletionTransaction"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("preAuthCompletionTransaction")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "reactivate_terminal", cmap(4,
        "fields", clist(7,
          cmap(2,
            "name", v_str("corporateUuid"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("packageOrderUuid"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("productOrderUuid"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("reactivationReason"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminalId"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("reactivate_terminal"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/reactivateTerminal"),
                "parts", clist(1,
                  v_str("reactivateTerminal")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "refund_transaction", cmap(4,
        "fields", clist(40,
          cmap(2,
            "name", v_str("acquirerId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("acquirerName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("actualBonusPoints"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("amount"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$INTEGER`"))),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("authorizationCode"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("balanceAmount"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("cardBrand"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("cardNumber"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("clientId"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("currency"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("cvc"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("ecData"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("ecrData"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("emvData"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("exchangeFee"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("exchangeRate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("languageCode"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("merchantAddress"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("merchantName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("merchantNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("messageType"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("originalTraceNumber"),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("originalTransactionId"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("password"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("paymentReason"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("receiptFooter"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("receiptHeader"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("receiptLayout"),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("receiptNumber"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("serialNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("svc"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminalId"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("terminalLocation"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("traceNumber"),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("transactionDate"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("transactionId"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("txType"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("userData"),
            "type", v_str("`$STRING`"))),
        "name", v_str("refund_transaction"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/refundTransaction"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("refundTransaction")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "register_tecs_company", cmap(4,
        "fields", clist(8,
          cmap(3,
            "name", v_str("corporateUuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("packageOrderUuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("partnerId"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("partnerName"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("productOrderUuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("templateName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("register_tecs_company"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/registerTecsCompany"),
                "parts", clist(1,
                  v_str("registerTecsCompany")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "register_terminal", cmap(4,
        "fields", clist(18,
          cmap(2,
            "name", v_str("additionalData"),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("corporateUuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("packageOrderUuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("productOrderUuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("tecsWebSecretKey"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("templateName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminalCountryCode"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("terminalId"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("terminalIdAcq"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminalLanguageCode"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminalLocation"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("terminalSerialNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("tokenIOAlias"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("tokenIOIban"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("tokenIOMemberId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("webShopUrl"),
            "type", v_str("`$STRING`"))),
        "name", v_str("register_terminal"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/registerTerminal"),
                "parts", clist(1,
                  v_str("registerTerminal")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "report_data", cmap(4,
        "fields", clist(10,
          cmap(2,
            "name", v_str("cardBrandReportData"),
            "type", v_str("`$ARRAY`")),
          cmap(4,
            "name", v_str("clearingDateFrom"),
            "req", v_bool(true),
            "short", v_str("Date and time in the format yyyy-MM-dd'T'HH:mm:ss"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("clearingDateTo"),
            "req", v_bool(true),
            "short", v_str("Date and time in the format yyyy-MM-dd'T'HH:mm:ss"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("corporateId"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("currency"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("sumOverCreditTx"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("sumOverDebitTx"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("terminalId"),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("report_data"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/digitalservices/reportData"),
                "parts", clist(3,
                  v_str("public"),
                  v_str("digitalservices"),
                  v_str("reportData")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "status_transaction", cmap(4,
        "fields", clist(50,
          cmap(2,
            "name", v_str("acquirerName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("acquirerTerminalId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("amount"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("applicationCryptogram"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("authorizationCode"),
            "short", v_str("Authorization code returned by the acquirer; null when not available"),
            "type", clist(2,
              v_str("`$ONE`"),
              clist(2,
                v_str("`$STRING`"),
                v_str("`$NULL`")))),
          cmap(2,
            "name", v_str("authorizationDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("cardBrand"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("cardEntry"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("cardExpiration"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("cardNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("clearingAmount"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("clearingBatchId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("clearingCurrency"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("clearingDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("clearingProcessedDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("clearingStatus"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("clientId"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("currency"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("cvm"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("ecrData"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("emvApplicationId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("emvApplicationLabel"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("merchantName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("merchantNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("originalClientId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("originalTerminalId"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("originalTransactionId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("paymentReason"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("receiptNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseCodeFromAS"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("retrievalReferenceNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("serviceCode"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("settlementStatus"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("sourceId"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("tecsengineResponseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("tecsengineResponseText"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("terminalEndOfDayDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("terminalId"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("terminalLocation"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("tipAmount"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("traceNumber"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("transactionClearingDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionSeqNumber"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("transactionServerDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionSource"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionType"),
            "type", v_str("`$STRING`"))),
        "name", v_str("status_transaction"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/statusTransaction"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("statusTransaction")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "store_terminal_parameter", cmap(4,
        "fields", clist(6,
          cmap(2,
            "name", v_str("acqTabNexo"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("configVersion"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("serialNumber"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("tidSent"),
            "type", v_str("`$STRING`"))),
        "name", v_str("store_terminal_parameter"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/storeTerminalParameters"),
                "parts", clist(1,
                  v_str("storeTerminalParameters")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "terminal_id", cmap(4,
        "fields", clist(5,
          cmap(3,
            "name", v_str("deviceSerialNumber"),
            "req", v_bool(true),
            "type", v_str("`$ARRAY`")),
          cmap(2,
            "name", v_str("duplicateTerminalIds"),
            "type", v_str("`$ARRAY`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("terminals"),
            "type", v_str("`$ARRAY`"))),
        "name", v_str("terminal_id"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/getTerminalId"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("getTerminalId")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "transaction_history", cmap(4,
        "fields", clist(29,
          cmap(2,
            "name", v_str("3DSecure"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("authorizationCode"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("cardBrand"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("clearingAmountFrom"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("clearingAmountTo"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("clearingCurrency"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("clearingStatus"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("corporateUUID"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("orderByTransactionDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("pagination"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("paymentTokenPublicId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("receiptNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("referencedTransactionId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("retrievalReferenceNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("sourceId"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("tecsengineResponseCodeFrom"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("tecsengineResponseCodeTo"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("terminalId"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("traceNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionAmountFrom"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionAmountTo"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionDateFrom"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionDateTo"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionHistories"),
            "type", v_str("`$ARRAY`")),
          cmap(2,
            "name", v_str("transactionId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionType"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("wallet"),
            "short", v_str("Filter by wallet type."),
            "type", v_str("`$STRING`"))),
        "name", v_str("transaction_history"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/mcom/transactionHistory"),
                "parts", clist(3,
                  v_str("public"),
                  v_str("mcom"),
                  v_str("transactionHistory")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/transactionHistory"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("transactionHistory")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "transactions_count", cmap(4,
        "fields", clist(6,
          cmap(2,
            "name", v_str("period"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("transactionDateFrom"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("transactionDateTo"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionsCount"),
            "type", v_str("`$ARRAY`"))),
        "name", v_str("transactions_count"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/countAuthorisedTransactions"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("countAuthorisedTransactions")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/countNotAuthorisedTransactions"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("countNotAuthorisedTransactions")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "transactions_count_card_brand", cmap(4,
        "fields", clist(6,
          cmap(2,
            "name", v_str("period"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("transactionDateFrom"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("transactionDateTo"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("transactionsCount"),
            "type", v_str("`$ARRAY`"))),
        "name", v_str("transactions_count_card_brand"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/countTransactionsByCardBrand"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("countTransactionsByCardBrand")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "transactions_turnover", cmap(4,
        "fields", clist(6,
          cmap(2,
            "name", v_str("period"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("transactionDateFrom"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("transactionDateTo"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("turnovers"),
            "type", v_str("`$ARRAY`"))),
        "name", v_str("transactions_turnover"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/transactionTurnover"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("transactionTurnover")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "update_merchant", cmap(4,
        "fields", clist(11,
          cmap(2,
            "name", v_str("city"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("corporateUuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("country"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("merchantCategoryCode"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("name"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("state"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("street"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("vuNummer"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("zipcode"),
            "type", v_str("`$STRING`"))),
        "name", v_str("update_merchant"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/updateMerchant"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("updateMerchant")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "update_template_xml", cmap(4,
        "fields", clist(4,
          cmap(2,
            "name", v_str("responseCode"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("responseMessage"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("templateName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("templateXml"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("update_template_xml"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/public/updateTemplateXml"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("updateTemplateXml")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "version", cmap(4,
        "fields", clist(3,
          cmap(2,
            "name", v_str("appName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("buildDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("version"),
            "type", v_str("`$STRING`"))),
        "name", v_str("version"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/public/version"),
                "parts", clist(2,
                  v_str("public"),
                  v_str("version")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Deliberately never freed: it lives for the life of the process, like any
// other program-lifetime singleton.
static voxgig_value* shared_config_val = NULL;

// The process-wide config, built once on first use.
//
// The returned value is SHARED: treat it as read-only. Callers that need to
// mutate should use make_config, which always returns a fresh copy.
voxgig_value* shared_config(void) {
  if (NULL == shared_config_val) {
    shared_config_val = make_config();
  }
  return shared_config_val;
}

Feature* feature_test_new(void);

Feature* make_feature(const char* name) {
  if (strcmp(name, "test") == 0) return feature_test_new();
  return feature_base_new();
}
