
const envlocal = __dirname + '/../../../.env.local'
require('../../utility').loadEnvLocal(envlocal)

const Path = require('node:path')
const Fs = require('node:fs')

const { test, describe, afterEach } = require('node:test')
const assert = require('node:assert')
const { createLiveTransport } = require('../../live-runner')
const { runLiveEntity } = require('../../live-entity')


const { BluefinTecsMerchantServicesSDK, BaseFeature, stdutil, config } = require('../../..')

const {
  envOverride,
  liveClientOptions,
  liveDelay,
  makeCtrl,
  makeMatch,
  makeReqdata,
  makeStepData,
  makeValid,
} = require('../../utility')


describe('PaymentManualEntity', async () => {

  // Per-test live pacing. Delay is read from sdk-test-control.json's
  // `test.live.delayMs`; only sleeps when BLUEFIN_TECS_MERCHANT_SERVICES_TEST_LIVE=TRUE.
  afterEach(liveDelay('BLUEFIN_TECS_MERCHANT_SERVICES_TEST_LIVE'))

  test('instance', async () => {
    const testsdk = BluefinTecsMerchantServicesSDK.test()
    const ent = testsdk.PaymentManual()
    assert(null != ent)
  })


  test('basic', async (t) => {

    
    const setup = basicSetup()
    if (setup.live) {
      return runLiveEntity(setup, {"active":true,"alias":{"field":{}},"fields":[{"active":true,"name":"acquirerName","req":false,"short":"Acquirer name parsed from KKG field","type":"`$STRING`","index$":0},{"active":true,"format":"int32","name":"amount","req":true,"short":"Transaction amount in minor units (cents)","type":"`$INTEGER`","index$":1},{"active":true,"name":"authorizationNumber","req":false,"short":"Authorization number from the gateway","type":"`$STRING`","index$":2},{"active":true,"name":"cardNumber","req":true,"short":"Card number - 12 to 19 digits, must pass Luhn validation","type":"`$STRING`","index$":3},{"active":true,"name":"cardType","req":false,"short":"Card type parsed from KKG field","type":"`$STRING`","index$":4},{"active":true,"name":"currency","req":true,"short":"Currency code - 3 uppercase letters (ISO 4217)","type":"`$STRING`","index$":5},{"active":true,"name":"cvc","req":false,"short":"Card verification code - 3-4 digits (optional)","type":"`$STRING`","index$":6},{"active":true,"name":"dateTimeTx","req":false,"short":"Date and time of the transaction","type":"`$STRING`","index$":7},{"active":true,"name":"expDate","req":true,"short":"Card expiry date in MMYY format","type":"`$STRING`","index$":8},{"active":true,"name":"merchantId","req":false,"short":"Merchant ID (VU-NUMMER)","type":"`$STRING`","index$":9},{"active":true,"name":"originalTransactionId","req":false,"short":"Original transaction ID from gateway","type":"`$STRING`","index$":10},{"active":true,"name":"password","req":false,"short":"Terminal password sent as Kennwort in TECS XML (optional)","type":"`$STRING`","index$":11},{"active":true,"name":"responseCode","req":false,"short":"Response code - 00 for success, otherwise error code","type":"`$STRING`","index$":12},{"active":true,"name":"responseMessage","req":false,"short":"Response message - 'Approved' for success, error description otherwise","type":"`$STRING`","index$":13},{"active":true,"name":"terminalId","op":{"create":{"req":true,"type":"`$STRING`"}},"req":false,"short":"Terminal ID used for the transaction","type":"`$STRING`","index$":14},{"active":true,"name":"transactionId","req":false,"short":"Transaction ID generated by the backend","type":"`$STRING`","index$":15},{"active":true,"name":"txtype","req":true,"short":"Transaction type","type":"`$STRING`","index$":16}],"name":"payment_manual","op":{"create":{"input":"data","name":"create","points":[{"active":true,"args":{},"contract":{"id":"POST /public/paymentManual","json":"{\"operationId\":\"paymentManual\",\"parameters\":[],\"protocol\":\"http\",\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"description\":\"Payment Manual request for processing card payments via TECS XML gateway\",\"properties\":{\"amount\":{\"description\":\"Transaction amount in minor units (cents)\",\"example\":1234,\"format\":\"int32\",\"minimum\":1,\"type\":\"integer\"},\"cardNumber\":{\"description\":\"Card number - 12 to 19 digits, must pass Luhn validation\",\"example\":\"5413330056003537\",\"minLength\":1,\"pattern\":\"^\\\\d{12,19}$\",\"type\":\"string\"},\"currency\":{\"description\":\"Currency code - 3 uppercase letters (ISO 4217)\",\"example\":\"EUR\",\"minLength\":1,\"pattern\":\"^[A-Z]{3}$\",\"type\":\"string\"},\"cvc\":{\"description\":\"Card verification code - 3-4 digits (optional)\",\"example\":\"123\",\"pattern\":\"^\\\\d{3,4}$\",\"type\":\"string\"},\"expDate\":{\"description\":\"Card expiry date in MMYY format\",\"example\":\"1027\",\"minLength\":1,\"pattern\":\"^(0[1-9]|1[0-2])\\\\d{2}$\",\"type\":\"string\"},\"password\":{\"description\":\"Terminal password sent as Kennwort in TECS XML (optional)\",\"example\":\"testPWD\",\"type\":\"string\"},\"terminalId\":{\"description\":\"Terminal ID - 8 digits\",\"example\":\"88092010\",\"minLength\":1,\"pattern\":\"^\\\\d{8}$\",\"type\":\"string\"},\"txtype\":{\"description\":\"Transaction type\",\"enum\":[\"SALE\",\"PRE-AUTH\"],\"example\":\"SALE\",\"minLength\":1,\"pattern\":\"^(SALE|PRE-AUTH)$\",\"type\":\"string\"}},\"required\":[\"amount\",\"cardNumber\",\"currency\",\"expDate\",\"terminalId\",\"txtype\"],\"type\":\"object\"}}},\"required\":true},\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"description\":\"Payment Manual response from TECS XML gateway\",\"properties\":{\"acquirerName\":{\"description\":\"Acquirer name parsed from KKG field\",\"example\":\"TECS Offline\",\"type\":\"string\"},\"authorizationNumber\":{\"description\":\"Authorization number from the gateway\",\"example\":68529,\"type\":\"string\"},\"cardType\":{\"description\":\"Card type parsed from KKG field\",\"example\":\"MASTERCARD\",\"type\":\"string\"},\"dateTimeTx\":{\"description\":\"Date and time of the transaction\",\"example\":\"20251008160321\",\"type\":\"string\"},\"merchantId\":{\"description\":\"Merchant ID (VU-NUMMER)\",\"example\":\"123456789012345\",\"type\":\"string\"},\"originalTransactionId\":{\"description\":\"Original transaction ID from gateway\",\"example\":20251008160321,\"type\":\"string\"},\"responseCode\":{\"description\":\"Response code - 00 for success, otherwise error code\",\"example\":\"00\",\"type\":\"string\"},\"responseMessage\":{\"description\":\"Response message - 'Approved' for success, error description otherwise\",\"example\":\"Approved\",\"type\":\"string\"},\"terminalId\":{\"description\":\"Terminal ID used for the transaction\",\"example\":\"88092010\",\"type\":\"string\"},\"transactionId\":{\"description\":\"Transaction ID generated by the backend\",\"example\":\"20251008160321\",\"type\":\"string\"}},\"type\":\"object\"}}},\"description\":\"Successful operation\"},\"400\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"responseCode\":{\"format\":\"int32\",\"type\":\"integer\"},\"responseMessage\":{\"type\":\"string\"}},\"type\":\"object\"}}},\"description\":\"\\n* Invalid JSON\\n* Invalid terminalId - must be 8 digits\\n* Invalid currency - must be 3 uppercase letters\\n* Invalid amount - must be greater than 0\\n* Invalid txtype - must be SALE or PRE-AUTH\\n* Invalid cardNumber - must be 12-19 digits and Luhn-valid\\n* Invalid expDate - must be MMYY format and not expired\\n* Invalid cvc - must be 3-4 digits if provided\\n\"},\"401\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"responseCode\":{\"format\":\"int32\",\"type\":\"integer\"},\"responseMessage\":{\"type\":\"string\"}},\"type\":\"object\"}}},\"description\":\"Unauthorized - Authentication failed\"},\"403\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"responseCode\":{\"format\":\"int32\",\"type\":\"integer\"},\"responseMessage\":{\"type\":\"string\"}},\"type\":\"object\"}}},\"description\":\"Forbidden - Missing role: BO_VIRTUAL_TERMINAL or VIRTUAL_TERMINAL\"},\"500\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"responseCode\":{\"format\":\"int32\",\"type\":\"integer\"},\"responseMessage\":{\"type\":\"string\"}},\"type\":\"object\"}}},\"description\":\"Internal server error\"},\"502\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"responseCode\":{\"format\":\"int32\",\"type\":\"integer\"},\"responseMessage\":{\"type\":\"string\"}},\"type\":\"object\"}}},\"description\":\"Gateway error - TECS XML gateway error or invalid XML response\"}},\"security\":[{\"bearer-key\":[]}],\"securitySchemes\":{\"basic-key\":{\"scheme\":\"basic\",\"type\":\"http\"},\"bearer-key\":{\"bearerFormat\":\"JWT\",\"scheme\":\"bearer\",\"type\":\"http\"},\"tecsweb-key\":{\"description\":\"TecsWeb token\",\"in\":\"header\",\"name\":\"TecsWebToken\",\"type\":\"apiKey\"}},\"securitySource\":\"operation\"}","source":"openapi3","version":1},"kind":"http","method":"POST","orig":"/public/paymentManual","segments":[{"lit":"public"},{"lit":"paymentManual"}],"select":{},"transform":{"req":"`reqdata`","res":"`body`"},"index$":0}],"key$":"create"}},"relations":{"ancestors":[]},"key$":"payment_manual","name__orig":"payment_manual","Name":"PaymentManual","name_":"payment_manual","name-":"payment-manual","NAME":"PAYMENT_MANUAL","index$":21}, {"active":true,"entity":"payment_manual","key$":"BasicPaymentManualFlow","kind":"basic","name":"BasicPaymentManualFlow","param":{},"step":[{"active":true,"data":{},"input":{"ref":"payment_manual_ref01"},"match":{},"op":"create","spec":[],"valid":[],"index$":0}]}, 'PaymentManual')
    }
    const client = setup.client
    const struct = setup.struct

    const isempty = struct.isempty
    const select = struct.select


    // CREATE
    const payment_manual_ref01_ent = client.PaymentManual()
    let payment_manual_ref01_data = setup.data.new.payment_manual['payment_manual_ref01']

    payment_manual_ref01_data = (await payment_manual_ref01_ent.create(payment_manual_ref01_data)).data()
    assert(null != payment_manual_ref01_data)


  })
})



function basicSetup(extra) {
  // TODO: fix test def options
  const options = {} // null

  // TODO: needs test utility to resolve path
  const entityDataFile =
    Path.resolve(__dirname,
      '../../../../.sdk/test/entity/payment_manual/PaymentManualTestData.json')

  // TODO: file ready util needed?
  const entityDataSource = Fs.readFileSync(entityDataFile).toString('utf8')

  // TODO: need a xlang JSON parse utility in voxgig/struct with better error msgs
  const entityData = JSON.parse(entityDataSource)

  options.entity = entityData.existing

  let client = BluefinTecsMerchantServicesSDK.test(options, extra)
  const struct = client.utility().struct
  const merge = struct.merge
  const transform = struct.transform

  let idmap = transform(
    ['payment_manual01','payment_manual02','payment_manual03'],
    {
      '`$PACK`': ['', {
        '`$KEY`': '`$COPY`',
        '`$VAL`': ['`$FORMAT`', 'upper', '`$COPY`']
      }]
    })

  const env = envOverride({
    'BLUEFIN_TECS_MERCHANT_SERVICES_TEST_PAYMENT_MANUAL_ENTID': idmap,
    'BLUEFIN_TECS_MERCHANT_SERVICES_TEST_LIVE': 'FALSE',
    'BLUEFIN_TECS_MERCHANT_SERVICES_TEST_EXPLAIN': 'FALSE',
    'BLUEFIN_TECS_MERCHANT_SERVICES_APIKEY': '',
  })

  idmap = env['BLUEFIN_TECS_MERCHANT_SERVICES_TEST_PAYMENT_MANUAL_ENTID']

  const live = 'TRUE' === env.BLUEFIN_TECS_MERCHANT_SERVICES_TEST_LIVE
  const transport = createLiveTransport()
  if (live) {
    const rawIds = process.env['BLUEFIN_TECS_MERCHANT_SERVICES_TEST_PAYMENT_MANUAL_ENTID']
    idmap = rawIds && rawIds.trim() ? JSON.parse(rawIds) : {}
    if (!idmap || Array.isArray(idmap) || typeof idmap !== 'object') {
      throw new Error('Live ENTID must be a JSON object')
    }
    client = new BluefinTecsMerchantServicesSDK(merge([
      // FIRST, so the generated fields below win: sdk-test-control.json's
      // test.client.options adds to the live client, it does not redirect it.
      liveClientOptions(),
      {
        apikey: env.BLUEFIN_TECS_MERCHANT_SERVICES_APIKEY,
      },
      // 'extra || {}', not a bare 'extra': struct.merge returns UNDEFINED when
      // the last entry is undefined, and basicSetup is normally called with no
      // argument at all - so a bare 'extra' silently discarded the apikey and
      // server values above and handed the SDK undefined.
      extra || {},
      { system: { fetch: transport.fetch } }
    ]))
  }

  const setup = {
    idmap,
    env,
    options,
    client,
    struct,
    data: entityData,
    explain: 'TRUE' === env.BLUEFIN_TECS_MERCHANT_SERVICES_TEST_EXPLAIN,
    live,
    transport,
    now: Date.now(),
  }

  return setup
}
  
