// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/bluefin-tecs-merchant-services-sdk/go"
)

// registerSDKWords installs three native boru words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word. Both
// overloads are all-forward (BarrierAllForward), so args are collected
// from the tokens following the word.
func registerSDKWords(r *eng.Registry, client *sdk.BluefinTecsMerchantServicesSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.BluefinTecsMerchantServicesSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.BluefinTecsMerchantServicesSDK, name string) (sdk.BluefinTecsMerchantServicesEntity, error) {
	switch strings.ToLower(name) {
	case "cancel_transaction":
		return client.CancelTransaction(nil), nil
	case "check_card_black_listed":
		return client.CheckCardBlackListed(nil), nil
	case "create_product":
		return client.CreateProduct(nil), nil
	case "deactivate_terminal":
		return client.DeactivateTerminal(nil), nil
	case "digital_services_api":
		return client.DigitalServicesApi(nil), nil
	case "ec_data_ecom":
		return client.EcDataEcom(nil), nil
	case "ecom_parameter":
		return client.EcomParameter(nil), nil
	case "ecr_data":
		return client.EcrData(nil), nil
	case "emv_data":
		return client.EmvData(nil), nil
	case "enable_acquiring":
		return client.EnableAcquiring(nil), nil
	case "get_merchant_contract_number":
		return client.GetMerchantContractNumber(nil), nil
	case "get_template_xml":
		return client.GetTemplateXml(nil), nil
	case "introduce_mandator":
		return client.IntroduceMandator(nil), nil
	case "introduce_package":
		return client.IntroducePackage(nil), nil
	case "keep_alive":
		return client.KeepAlive(nil), nil
	case "list_terminal":
		return client.ListTerminal(nil), nil
	case "mandator_clearing_export":
		return client.MandatorClearingExport(nil), nil
	case "mandator_clearing_export_download":
		return client.MandatorClearingExportDownload(nil), nil
	case "mandator_clearing_export_summary":
		return client.MandatorClearingExportSummary(nil), nil
	case "merchant_portal_services_api":
		return client.MerchantPortalServicesApi(nil), nil
	case "move_tid":
		return client.MoveTid(nil), nil
	case "payment_manual":
		return client.PaymentManual(nil), nil
	case "payment_sred":
		return client.PaymentSred(nil), nil
	case "pre_auth_transaction_completion":
		return client.PreAuthTransactionCompletion(nil), nil
	case "reactivate_terminal":
		return client.ReactivateTerminal(nil), nil
	case "refund_transaction":
		return client.RefundTransaction(nil), nil
	case "register_tecs_company":
		return client.RegisterTecsCompany(nil), nil
	case "register_terminal":
		return client.RegisterTerminal(nil), nil
	case "report_data":
		return client.ReportData(nil), nil
	case "status_transaction":
		return client.StatusTransaction(nil), nil
	case "store_terminal_parameter":
		return client.StoreTerminalParameter(nil), nil
	case "terminal_id":
		return client.TerminalId(nil), nil
	case "transaction_history":
		return client.TransactionHistory(nil), nil
	case "transactions_count":
		return client.TransactionsCount(nil), nil
	case "transactions_count_card_brand":
		return client.TransactionsCountCardBrand(nil), nil
	case "transactions_turnover":
		return client.TransactionsTurnover(nil), nil
	case "update_merchant":
		return client.UpdateMerchant(nil), nil
	case "update_template_xml":
		return client.UpdateTemplateXml(nil), nil
	case "version":
		return client.Version(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
