// BluefinTecsMerchantServices SDK entities (generated).

#ifndef SDK_ENTITY_ENTITIES_HPP
#define SDK_ENTITY_ENTITIES_HPP

#include "cancel_transaction.hpp"
#include "check_card_black_listed.hpp"
#include "create_product.hpp"
#include "deactivate_terminal.hpp"
#include "digital_services_api.hpp"
#include "ec_data_ecom.hpp"
#include "ecom_parameter.hpp"
#include "ecr_data.hpp"
#include "emv_data.hpp"
#include "enable_acquiring.hpp"
#include "get_merchant_contract_number.hpp"
#include "get_template_xml.hpp"
#include "introduce_mandator.hpp"
#include "introduce_package.hpp"
#include "keep_alive.hpp"
#include "list_terminal.hpp"
#include "mandator_clearing_export.hpp"
#include "mandator_clearing_export_download.hpp"
#include "mandator_clearing_export_summary.hpp"
#include "merchant_portal_services_api.hpp"
#include "move_tid.hpp"
#include "payment_manual.hpp"
#include "payment_sred.hpp"
#include "pre_auth_transaction_completion.hpp"
#include "reactivate_terminal.hpp"
#include "refund_transaction.hpp"
#include "register_tecs_company.hpp"
#include "register_terminal.hpp"
#include "report_data.hpp"
#include "status_transaction.hpp"
#include "store_terminal_parameter.hpp"
#include "terminal_id.hpp"
#include "transaction_history.hpp"
#include "transactions_count.hpp"
#include "transactions_count_card_brand.hpp"
#include "transactions_turnover.hpp"
#include "update_merchant.hpp"
#include "update_template_xml.hpp"
#include "version.hpp"

#endif // SDK_ENTITY_ENTITIES_HPP
