// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/bluefin-tecs-merchant-services-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"cancel_transaction | check_card_black_listed | create_product | deactivate_terminal | digital_services_api | ec_data_ecom | ecom_parameter | ecr_data | emv_data | enable_acquiring | get_merchant_contract_number | get_template_xml | introduce_mandator | introduce_package | keep_alive | list_terminal | mandator_clearing_export | mandator_clearing_export_download | mandator_clearing_export_summary | merchant_portal_services_api | move_tid | payment_manual | payment_sred | pre_auth_transaction_completion | reactivate_terminal | refund_transaction | register_tecs_company | register_terminal | report_data | status_transaction | store_terminal_parameter | terminal_id | transaction_history | transactions_count | transactions_count_card_brand | transactions_turnover | update_merchant | update_template_xml | version"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.BluefinTecsMerchantServicesSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "bluefin-tecs-merchant-services_list",
		Description: "List records from BluefinTecsMerchantServices. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "bluefin-tecs-merchant-services_load",
		Description: "Load a single record from BluefinTecsMerchantServices. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.BluefinTecsMerchantServicesSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.BluefinTecsMerchantServicesSDK, name string) (sdk.BluefinTecsMerchantServicesEntity, error) {
	switch strings.ToLower(name) {
	case "cancel_transaction":
		return client.CancelTransaction(nil), nil
	case "check_card_black_listed":
		return client.CheckCardBlackListed(nil), nil
	case "create_product":
		return client.CreateProduct(nil), nil
	case "deactivate_terminal":
		return client.DeactivateTerminal(nil), nil
	case "digital_services_api":
		return client.DigitalServicesApi(nil), nil
	case "ec_data_ecom":
		return client.EcDataEcom(nil), nil
	case "ecom_parameter":
		return client.EcomParameter(nil), nil
	case "ecr_data":
		return client.EcrData(nil), nil
	case "emv_data":
		return client.EmvData(nil), nil
	case "enable_acquiring":
		return client.EnableAcquiring(nil), nil
	case "get_merchant_contract_number":
		return client.GetMerchantContractNumber(nil), nil
	case "get_template_xml":
		return client.GetTemplateXml(nil), nil
	case "introduce_mandator":
		return client.IntroduceMandator(nil), nil
	case "introduce_package":
		return client.IntroducePackage(nil), nil
	case "keep_alive":
		return client.KeepAlive(nil), nil
	case "list_terminal":
		return client.ListTerminal(nil), nil
	case "mandator_clearing_export":
		return client.MandatorClearingExport(nil), nil
	case "mandator_clearing_export_download":
		return client.MandatorClearingExportDownload(nil), nil
	case "mandator_clearing_export_summary":
		return client.MandatorClearingExportSummary(nil), nil
	case "merchant_portal_services_api":
		return client.MerchantPortalServicesApi(nil), nil
	case "move_tid":
		return client.MoveTid(nil), nil
	case "payment_manual":
		return client.PaymentManual(nil), nil
	case "payment_sred":
		return client.PaymentSred(nil), nil
	case "pre_auth_transaction_completion":
		return client.PreAuthTransactionCompletion(nil), nil
	case "reactivate_terminal":
		return client.ReactivateTerminal(nil), nil
	case "refund_transaction":
		return client.RefundTransaction(nil), nil
	case "register_tecs_company":
		return client.RegisterTecsCompany(nil), nil
	case "register_terminal":
		return client.RegisterTerminal(nil), nil
	case "report_data":
		return client.ReportData(nil), nil
	case "status_transaction":
		return client.StatusTransaction(nil), nil
	case "store_terminal_parameter":
		return client.StoreTerminalParameter(nil), nil
	case "terminal_id":
		return client.TerminalId(nil), nil
	case "transaction_history":
		return client.TransactionHistory(nil), nil
	case "transactions_count":
		return client.TransactionsCount(nil), nil
	case "transactions_count_card_brand":
		return client.TransactionsCountCardBrand(nil), nil
	case "transactions_turnover":
		return client.TransactionsTurnover(nil), nil
	case "update_merchant":
		return client.UpdateMerchant(nil), nil
	case "update_template_xml":
		return client.UpdateTemplateXml(nil), nil
	case "version":
		return client.Version(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
