(* BluefinTecsMerchantServices SDK client (generated by @voxgig/sdkgen).
 *
 * The SDK "object" is the runtime sdk_client record (see Sdk_types). These
 * constructors wire the embedded config + feature factory (Sdk_config) into
 * the API-agnostic client builders (Sdk_features.make_client_base / sdk_test).
 * Entity accessors return an entity_obj whose CRUD closures run the pipeline. *)

open Voxgig_struct
open Sdk_types
open Sdk_features

(* Construct a live client from options (Noval for defaults). *)
let make (options : value) : sdk_client =
  make_client_base
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    options

(* No-argument convenience constructor. *)
let make0 () : sdk_client = make Noval

(* Construct a client in test mode (in-memory mock transport). *)
let test () : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    Noval Noval

(* Test-mode client with explicit test / sdk options. *)
let test_with (testopts : value) (sdkopts : value) : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    testopts sdkopts

(* Low-level escape hatches (raw transport call / request preparation). *)
let direct (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.direct client fetchargs

let prepare (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.prepare client fetchargs

(* CancelTransaction entity bound to a client:  cancel_transaction client entopts *)
let cancel_transaction (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_cancel_transaction.make client entopts

(* CheckCardBlackListed entity bound to a client:  check_card_black_listed client entopts *)
let check_card_black_listed (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_check_card_black_listed.make client entopts

(* CreateProduct entity bound to a client:  create_product client entopts *)
let create_product (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_create_product.make client entopts

(* DeactivateTerminal entity bound to a client:  deactivate_terminal client entopts *)
let deactivate_terminal (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_deactivate_terminal.make client entopts

(* DigitalServicesApi entity bound to a client:  digital_services_api client entopts *)
let digital_services_api (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_digital_services_api.make client entopts

(* EcDataEcom entity bound to a client:  ec_data_ecom client entopts *)
let ec_data_ecom (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_ec_data_ecom.make client entopts

(* EcomParameter entity bound to a client:  ecom_parameter client entopts *)
let ecom_parameter (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_ecom_parameter.make client entopts

(* EcrData entity bound to a client:  ecr_data client entopts *)
let ecr_data (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_ecr_data.make client entopts

(* EmvData entity bound to a client:  emv_data client entopts *)
let emv_data (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_emv_data.make client entopts

(* EnableAcquiring entity bound to a client:  enable_acquiring client entopts *)
let enable_acquiring (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_enable_acquiring.make client entopts

(* GetMerchantContractNumber entity bound to a client:  get_merchant_contract_number client entopts *)
let get_merchant_contract_number (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_get_merchant_contract_number.make client entopts

(* GetTemplateXml entity bound to a client:  get_template_xml client entopts *)
let get_template_xml (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_get_template_xml.make client entopts

(* IntroduceMandator entity bound to a client:  introduce_mandator client entopts *)
let introduce_mandator (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_introduce_mandator.make client entopts

(* IntroducePackage entity bound to a client:  introduce_package client entopts *)
let introduce_package (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_introduce_package.make client entopts

(* KeepAlive entity bound to a client:  keep_alive client entopts *)
let keep_alive (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_keep_alive.make client entopts

(* ListTerminal entity bound to a client:  list_terminal client entopts *)
let list_terminal (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_list_terminal.make client entopts

(* MandatorClearingExport entity bound to a client:  mandator_clearing_export client entopts *)
let mandator_clearing_export (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_mandator_clearing_export.make client entopts

(* MandatorClearingExportDownload entity bound to a client:  mandator_clearing_export_download client entopts *)
let mandator_clearing_export_download (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_mandator_clearing_export_download.make client entopts

(* MandatorClearingExportSummary entity bound to a client:  mandator_clearing_export_summary client entopts *)
let mandator_clearing_export_summary (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_mandator_clearing_export_summary.make client entopts

(* MerchantPortalServicesApi entity bound to a client:  merchant_portal_services_api client entopts *)
let merchant_portal_services_api (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_merchant_portal_services_api.make client entopts

(* MoveTid entity bound to a client:  move_tid client entopts *)
let move_tid (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_move_tid.make client entopts

(* PaymentManual entity bound to a client:  payment_manual client entopts *)
let payment_manual (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_payment_manual.make client entopts

(* PaymentSred entity bound to a client:  payment_sred client entopts *)
let payment_sred (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_payment_sred.make client entopts

(* PreAuthTransactionCompletion entity bound to a client:  pre_auth_transaction_completion client entopts *)
let pre_auth_transaction_completion (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_pre_auth_transaction_completion.make client entopts

(* ReactivateTerminal entity bound to a client:  reactivate_terminal client entopts *)
let reactivate_terminal (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_reactivate_terminal.make client entopts

(* RefundTransaction entity bound to a client:  refund_transaction client entopts *)
let refund_transaction (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_refund_transaction.make client entopts

(* RegisterTecsCompany entity bound to a client:  register_tecs_company client entopts *)
let register_tecs_company (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_register_tecs_company.make client entopts

(* RegisterTerminal entity bound to a client:  register_terminal client entopts *)
let register_terminal (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_register_terminal.make client entopts

(* ReportData entity bound to a client:  report_data client entopts *)
let report_data (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_report_data.make client entopts

(* StatusTransaction entity bound to a client:  status_transaction client entopts *)
let status_transaction (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_status_transaction.make client entopts

(* StoreTerminalParameter entity bound to a client:  store_terminal_parameter client entopts *)
let store_terminal_parameter (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_store_terminal_parameter.make client entopts

(* TerminalId entity bound to a client:  terminal_id client entopts *)
let terminal_id (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_terminal_id.make client entopts

(* TransactionHistory entity bound to a client:  transaction_history client entopts *)
let transaction_history (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_transaction_history.make client entopts

(* TransactionsCount entity bound to a client:  transactions_count client entopts *)
let transactions_count (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_transactions_count.make client entopts

(* TransactionsCountCardBrand entity bound to a client:  transactions_count_card_brand client entopts *)
let transactions_count_card_brand (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_transactions_count_card_brand.make client entopts

(* TransactionsTurnover entity bound to a client:  transactions_turnover client entopts *)
let transactions_turnover (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_transactions_turnover.make client entopts

(* UpdateMerchant entity bound to a client:  update_merchant client entopts *)
let update_merchant (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_update_merchant.make client entopts

(* UpdateTemplateXml entity bound to a client:  update_template_xml client entopts *)
let update_template_xml (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_update_template_xml.make client entopts

(* Version entity bound to a client:  version client entopts *)
let version (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_version.make client entopts
