-- BluefinTecsMerchantServices SDK public client (generated by @voxgig/sdkgen).
--
-- SDK constructors (newSdk / testSdk) and one accessor per entity. Entities
-- are generic — every accessor calls the config-driven F.makeEntity, so the
-- operation pipeline is identical for every entity and every API.

module SdkClient
  ( module SdkTypes
  , newSdk
  , newSdk0
  , testSdk
  , testSdk0
  , cancel_transaction
  , check_card_black_listed
  , create_product
  , deactivate_terminal
  , digital_services_api
  , ec_data_ecom
  , ecom_parameter
  , ecr_data
  , emv_data
  , enable_acquiring
  , get_merchant_contract_number
  , get_template_xml
  , introduce_mandator
  , introduce_package
  , keep_alive
  , list_terminal
  , mandator_clearing_export
  , mandator_clearing_export_download
  , mandator_clearing_export_summary
  , merchant_portal_services_api
  , move_tid
  , payment_manual
  , payment_sred
  , pre_auth_transaction_completion
  , reactivate_terminal
  , refund_transaction
  , register_tecs_company
  , register_terminal
  , report_data
  , status_transaction
  , store_terminal_parameter
  , terminal_id
  , transaction_history
  , transactions_count
  , transactions_count_card_brand
  , transactions_turnover
  , update_merchant
  , update_template_xml
  , version
  ) where

import Data.IORef (readIORef)

import VoxgigStruct (Value (..))
import SdkTypes
import SdkConfig (makeConfig, makeFeature)
import qualified SdkFeatures as F

-- | Construct a live SDK client from an options map (Noval for defaults).
newSdk :: Value -> IO Client
newSdk options = do
  cfg <- makeConfig
  F.makeClientBase cfg makeFeature options

-- | No-argument convenience constructor.
newSdk0 :: IO Client
newSdk0 = newSdk VNoval

-- | Construct a test-mode SDK: testSdk testopts sdkopts.
testSdk :: Value -> Value -> IO Client
testSdk testopts sdkopts = do
  cfg <- makeConfig
  F.sdkTest cfg makeFeature testopts sdkopts

-- | No-argument convenience test constructor.
testSdk0 :: IO Client
testSdk0 = testSdk VNoval VNoval

-- | The active client mode ("live" or "test").
clientMode :: Client -> IO String
clientMode = readIORef . clMode

-- | The CancelTransaction entity bound to this client.
cancel_transaction :: Client -> Value -> IO Entity
cancel_transaction client entopts = F.makeEntity client "cancel_transaction" entopts

-- | The CheckCardBlackListed entity bound to this client.
check_card_black_listed :: Client -> Value -> IO Entity
check_card_black_listed client entopts = F.makeEntity client "check_card_black_listed" entopts

-- | The CreateProduct entity bound to this client.
create_product :: Client -> Value -> IO Entity
create_product client entopts = F.makeEntity client "create_product" entopts

-- | The DeactivateTerminal entity bound to this client.
deactivate_terminal :: Client -> Value -> IO Entity
deactivate_terminal client entopts = F.makeEntity client "deactivate_terminal" entopts

-- | The DigitalServicesApi entity bound to this client.
digital_services_api :: Client -> Value -> IO Entity
digital_services_api client entopts = F.makeEntity client "digital_services_api" entopts

-- | The EcDataEcom entity bound to this client.
ec_data_ecom :: Client -> Value -> IO Entity
ec_data_ecom client entopts = F.makeEntity client "ec_data_ecom" entopts

-- | The EcomParameter entity bound to this client.
ecom_parameter :: Client -> Value -> IO Entity
ecom_parameter client entopts = F.makeEntity client "ecom_parameter" entopts

-- | The EcrData entity bound to this client.
ecr_data :: Client -> Value -> IO Entity
ecr_data client entopts = F.makeEntity client "ecr_data" entopts

-- | The EmvData entity bound to this client.
emv_data :: Client -> Value -> IO Entity
emv_data client entopts = F.makeEntity client "emv_data" entopts

-- | The EnableAcquiring entity bound to this client.
enable_acquiring :: Client -> Value -> IO Entity
enable_acquiring client entopts = F.makeEntity client "enable_acquiring" entopts

-- | The GetMerchantContractNumber entity bound to this client.
get_merchant_contract_number :: Client -> Value -> IO Entity
get_merchant_contract_number client entopts = F.makeEntity client "get_merchant_contract_number" entopts

-- | The GetTemplateXml entity bound to this client.
get_template_xml :: Client -> Value -> IO Entity
get_template_xml client entopts = F.makeEntity client "get_template_xml" entopts

-- | The IntroduceMandator entity bound to this client.
introduce_mandator :: Client -> Value -> IO Entity
introduce_mandator client entopts = F.makeEntity client "introduce_mandator" entopts

-- | The IntroducePackage entity bound to this client.
introduce_package :: Client -> Value -> IO Entity
introduce_package client entopts = F.makeEntity client "introduce_package" entopts

-- | The KeepAlive entity bound to this client.
keep_alive :: Client -> Value -> IO Entity
keep_alive client entopts = F.makeEntity client "keep_alive" entopts

-- | The ListTerminal entity bound to this client.
list_terminal :: Client -> Value -> IO Entity
list_terminal client entopts = F.makeEntity client "list_terminal" entopts

-- | The MandatorClearingExport entity bound to this client.
mandator_clearing_export :: Client -> Value -> IO Entity
mandator_clearing_export client entopts = F.makeEntity client "mandator_clearing_export" entopts

-- | The MandatorClearingExportDownload entity bound to this client.
mandator_clearing_export_download :: Client -> Value -> IO Entity
mandator_clearing_export_download client entopts = F.makeEntity client "mandator_clearing_export_download" entopts

-- | The MandatorClearingExportSummary entity bound to this client.
mandator_clearing_export_summary :: Client -> Value -> IO Entity
mandator_clearing_export_summary client entopts = F.makeEntity client "mandator_clearing_export_summary" entopts

-- | The MerchantPortalServicesApi entity bound to this client.
merchant_portal_services_api :: Client -> Value -> IO Entity
merchant_portal_services_api client entopts = F.makeEntity client "merchant_portal_services_api" entopts

-- | The MoveTid entity bound to this client.
move_tid :: Client -> Value -> IO Entity
move_tid client entopts = F.makeEntity client "move_tid" entopts

-- | The PaymentManual entity bound to this client.
payment_manual :: Client -> Value -> IO Entity
payment_manual client entopts = F.makeEntity client "payment_manual" entopts

-- | The PaymentSred entity bound to this client.
payment_sred :: Client -> Value -> IO Entity
payment_sred client entopts = F.makeEntity client "payment_sred" entopts

-- | The PreAuthTransactionCompletion entity bound to this client.
pre_auth_transaction_completion :: Client -> Value -> IO Entity
pre_auth_transaction_completion client entopts = F.makeEntity client "pre_auth_transaction_completion" entopts

-- | The ReactivateTerminal entity bound to this client.
reactivate_terminal :: Client -> Value -> IO Entity
reactivate_terminal client entopts = F.makeEntity client "reactivate_terminal" entopts

-- | The RefundTransaction entity bound to this client.
refund_transaction :: Client -> Value -> IO Entity
refund_transaction client entopts = F.makeEntity client "refund_transaction" entopts

-- | The RegisterTecsCompany entity bound to this client.
register_tecs_company :: Client -> Value -> IO Entity
register_tecs_company client entopts = F.makeEntity client "register_tecs_company" entopts

-- | The RegisterTerminal entity bound to this client.
register_terminal :: Client -> Value -> IO Entity
register_terminal client entopts = F.makeEntity client "register_terminal" entopts

-- | The ReportData entity bound to this client.
report_data :: Client -> Value -> IO Entity
report_data client entopts = F.makeEntity client "report_data" entopts

-- | The StatusTransaction entity bound to this client.
status_transaction :: Client -> Value -> IO Entity
status_transaction client entopts = F.makeEntity client "status_transaction" entopts

-- | The StoreTerminalParameter entity bound to this client.
store_terminal_parameter :: Client -> Value -> IO Entity
store_terminal_parameter client entopts = F.makeEntity client "store_terminal_parameter" entopts

-- | The TerminalId entity bound to this client.
terminal_id :: Client -> Value -> IO Entity
terminal_id client entopts = F.makeEntity client "terminal_id" entopts

-- | The TransactionHistory entity bound to this client.
transaction_history :: Client -> Value -> IO Entity
transaction_history client entopts = F.makeEntity client "transaction_history" entopts

-- | The TransactionsCount entity bound to this client.
transactions_count :: Client -> Value -> IO Entity
transactions_count client entopts = F.makeEntity client "transactions_count" entopts

-- | The TransactionsCountCardBrand entity bound to this client.
transactions_count_card_brand :: Client -> Value -> IO Entity
transactions_count_card_brand client entopts = F.makeEntity client "transactions_count_card_brand" entopts

-- | The TransactionsTurnover entity bound to this client.
transactions_turnover :: Client -> Value -> IO Entity
transactions_turnover client entopts = F.makeEntity client "transactions_turnover" entopts

-- | The UpdateMerchant entity bound to this client.
update_merchant :: Client -> Value -> IO Entity
update_merchant client entopts = F.makeEntity client "update_merchant" entopts

-- | The UpdateTemplateXml entity bound to this client.
update_template_xml :: Client -> Value -> IO Entity
update_template_xml client entopts = F.makeEntity client "update_template_xml" entopts

-- | The Version entity bound to this client.
version :: Client -> Value -> IO Entity
version client entopts = F.makeEntity client "version" entopts

