;; BluefinTecsMerchantServices SDK public API (generated by @voxgig/sdkgen).
(ns sdk.api
  (:require [sdk.client :as client]
            [sdk.entity.cancel_transaction :as e-cancel_transaction]
            [sdk.entity.check_card_black_listed :as e-check_card_black_listed]
            [sdk.entity.create_product :as e-create_product]
            [sdk.entity.deactivate_terminal :as e-deactivate_terminal]
            [sdk.entity.digital_services_api :as e-digital_services_api]
            [sdk.entity.ec_data_ecom :as e-ec_data_ecom]
            [sdk.entity.ecom_parameter :as e-ecom_parameter]
            [sdk.entity.ecr_data :as e-ecr_data]
            [sdk.entity.emv_data :as e-emv_data]
            [sdk.entity.enable_acquiring :as e-enable_acquiring]
            [sdk.entity.get_merchant_contract_number :as e-get_merchant_contract_number]
            [sdk.entity.get_template_xml :as e-get_template_xml]
            [sdk.entity.introduce_mandator :as e-introduce_mandator]
            [sdk.entity.introduce_package :as e-introduce_package]
            [sdk.entity.keep_alive :as e-keep_alive]
            [sdk.entity.list_terminal :as e-list_terminal]
            [sdk.entity.mandator_clearing_export :as e-mandator_clearing_export]
            [sdk.entity.mandator_clearing_export_download :as e-mandator_clearing_export_download]
            [sdk.entity.mandator_clearing_export_summary :as e-mandator_clearing_export_summary]
            [sdk.entity.merchant_portal_services_api :as e-merchant_portal_services_api]
            [sdk.entity.move_tid :as e-move_tid]
            [sdk.entity.payment_manual :as e-payment_manual]
            [sdk.entity.payment_sred :as e-payment_sred]
            [sdk.entity.pre_auth_transaction_completion :as e-pre_auth_transaction_completion]
            [sdk.entity.reactivate_terminal :as e-reactivate_terminal]
            [sdk.entity.refund_transaction :as e-refund_transaction]
            [sdk.entity.register_tecs_company :as e-register_tecs_company]
            [sdk.entity.register_terminal :as e-register_terminal]
            [sdk.entity.report_data :as e-report_data]
            [sdk.entity.status_transaction :as e-status_transaction]
            [sdk.entity.store_terminal_parameter :as e-store_terminal_parameter]
            [sdk.entity.terminal_id :as e-terminal_id]
            [sdk.entity.transaction_history :as e-transaction_history]
            [sdk.entity.transactions_count :as e-transactions_count]
            [sdk.entity.transactions_count_card_brand :as e-transactions_count_card_brand]
            [sdk.entity.transactions_turnover :as e-transactions_turnover]
            [sdk.entity.update_merchant :as e-update_merchant]
            [sdk.entity.update_template_xml :as e-update_template_xml]
            [sdk.entity.version :as e-version]))

(def make-sdk client/make-sdk)
(def test-sdk client/test-sdk)
(def direct client/direct)
(def graphql client/graphql)
(def prepare client/prepare)
(def options-map client/options-map)

;; CancelTransaction accessor: (cancel_transaction client data)
(defn cancel_transaction [client data] (e-cancel_transaction/make client data))

;; CheckCardBlackListed accessor: (check_card_black_listed client data)
(defn check_card_black_listed [client data] (e-check_card_black_listed/make client data))

;; CreateProduct accessor: (create_product client data)
(defn create_product [client data] (e-create_product/make client data))

;; DeactivateTerminal accessor: (deactivate_terminal client data)
(defn deactivate_terminal [client data] (e-deactivate_terminal/make client data))

;; DigitalServicesApi accessor: (digital_services_api client data)
(defn digital_services_api [client data] (e-digital_services_api/make client data))

;; EcDataEcom accessor: (ec_data_ecom client data)
(defn ec_data_ecom [client data] (e-ec_data_ecom/make client data))

;; EcomParameter accessor: (ecom_parameter client data)
(defn ecom_parameter [client data] (e-ecom_parameter/make client data))

;; EcrData accessor: (ecr_data client data)
(defn ecr_data [client data] (e-ecr_data/make client data))

;; EmvData accessor: (emv_data client data)
(defn emv_data [client data] (e-emv_data/make client data))

;; EnableAcquiring accessor: (enable_acquiring client data)
(defn enable_acquiring [client data] (e-enable_acquiring/make client data))

;; GetMerchantContractNumber accessor: (get_merchant_contract_number client data)
(defn get_merchant_contract_number [client data] (e-get_merchant_contract_number/make client data))

;; GetTemplateXml accessor: (get_template_xml client data)
(defn get_template_xml [client data] (e-get_template_xml/make client data))

;; IntroduceMandator accessor: (introduce_mandator client data)
(defn introduce_mandator [client data] (e-introduce_mandator/make client data))

;; IntroducePackage accessor: (introduce_package client data)
(defn introduce_package [client data] (e-introduce_package/make client data))

;; KeepAlive accessor: (keep_alive client data)
(defn keep_alive [client data] (e-keep_alive/make client data))

;; ListTerminal accessor: (list_terminal client data)
(defn list_terminal [client data] (e-list_terminal/make client data))

;; MandatorClearingExport accessor: (mandator_clearing_export client data)
(defn mandator_clearing_export [client data] (e-mandator_clearing_export/make client data))

;; MandatorClearingExportDownload accessor: (mandator_clearing_export_download client data)
(defn mandator_clearing_export_download [client data] (e-mandator_clearing_export_download/make client data))

;; MandatorClearingExportSummary accessor: (mandator_clearing_export_summary client data)
(defn mandator_clearing_export_summary [client data] (e-mandator_clearing_export_summary/make client data))

;; MerchantPortalServicesApi accessor: (merchant_portal_services_api client data)
(defn merchant_portal_services_api [client data] (e-merchant_portal_services_api/make client data))

;; MoveTid accessor: (move_tid client data)
(defn move_tid [client data] (e-move_tid/make client data))

;; PaymentManual accessor: (payment_manual client data)
(defn payment_manual [client data] (e-payment_manual/make client data))

;; PaymentSred accessor: (payment_sred client data)
(defn payment_sred [client data] (e-payment_sred/make client data))

;; PreAuthTransactionCompletion accessor: (pre_auth_transaction_completion client data)
(defn pre_auth_transaction_completion [client data] (e-pre_auth_transaction_completion/make client data))

;; ReactivateTerminal accessor: (reactivate_terminal client data)
(defn reactivate_terminal [client data] (e-reactivate_terminal/make client data))

;; RefundTransaction accessor: (refund_transaction client data)
(defn refund_transaction [client data] (e-refund_transaction/make client data))

;; RegisterTecsCompany accessor: (register_tecs_company client data)
(defn register_tecs_company [client data] (e-register_tecs_company/make client data))

;; RegisterTerminal accessor: (register_terminal client data)
(defn register_terminal [client data] (e-register_terminal/make client data))

;; ReportData accessor: (report_data client data)
(defn report_data [client data] (e-report_data/make client data))

;; StatusTransaction accessor: (status_transaction client data)
(defn status_transaction [client data] (e-status_transaction/make client data))

;; StoreTerminalParameter accessor: (store_terminal_parameter client data)
(defn store_terminal_parameter [client data] (e-store_terminal_parameter/make client data))

;; TerminalId accessor: (terminal_id client data)
(defn terminal_id [client data] (e-terminal_id/make client data))

;; TransactionHistory accessor: (transaction_history client data)
(defn transaction_history [client data] (e-transaction_history/make client data))

;; TransactionsCount accessor: (transactions_count client data)
(defn transactions_count [client data] (e-transactions_count/make client data))

;; TransactionsCountCardBrand accessor: (transactions_count_card_brand client data)
(defn transactions_count_card_brand [client data] (e-transactions_count_card_brand/make client data))

;; TransactionsTurnover accessor: (transactions_turnover client data)
(defn transactions_turnover [client data] (e-transactions_turnover/make client data))

;; UpdateMerchant accessor: (update_merchant client data)
(defn update_merchant [client data] (e-update_merchant/make client data))

;; UpdateTemplateXml accessor: (update_template_xml client data)
(defn update_template_xml [client data] (e-update_template_xml/make client data))

;; Version accessor: (version client data)
(defn version [client data] (e-version/make client data))
