;; BluefinTecsMerchantServices SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "cancel_transaction" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "acquirerId"
            "type" "`$STRING`")
          (vs/jm
            "name" "acquirerName"
            "type" "`$STRING`")
          (vs/jm
            "name" "actualBonusPoints"
            "type" "`$STRING`")
          (vs/jm
            "name" "amount"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$INTEGER`"))
            "type" "`$INTEGER`")
          (vs/jm
            "name" "authorizationCode"
            "type" "`$STRING`")
          (vs/jm
            "name" "balanceAmount"
            "type" "`$STRING`")
          (vs/jm
            "name" "cardBrand"
            "type" "`$STRING`")
          (vs/jm
            "name" "cardNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "clientId"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "currency"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "cvc"
            "type" "`$STRING`")
          (vs/jm
            "name" "ecData"
            "type" "`$STRING`")
          (vs/jm
            "name" "ecrData"
            "type" "`$STRING`")
          (vs/jm
            "name" "emvData"
            "type" "`$STRING`")
          (vs/jm
            "name" "exchangeFee"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "exchangeRate"
            "type" "`$STRING`")
          (vs/jm
            "name" "languageCode"
            "type" "`$STRING`")
          (vs/jm
            "name" "merchantAddress"
            "type" "`$STRING`")
          (vs/jm
            "name" "merchantName"
            "type" "`$STRING`")
          (vs/jm
            "name" "merchantNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "messageType"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "originalTraceNumber"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "originalTransactionId"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "password"
            "type" "`$STRING`")
          (vs/jm
            "name" "paymentReason"
            "type" "`$STRING`")
          (vs/jm
            "name" "receiptFooter"
            "type" "`$STRING`")
          (vs/jm
            "name" "receiptHeader"
            "type" "`$STRING`")
          (vs/jm
            "name" "receiptLayout"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "receiptNumber"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "serialNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "svc"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalId"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "terminalLocation"
            "type" "`$STRING`")
          (vs/jm
            "name" "traceNumber"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "transactionDate"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionId"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "txType"
            "type" "`$STRING`")
          (vs/jm
            "name" "userData"
            "type" "`$STRING`"))
        "name" "cancel_transaction"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/cancelTransaction"
                "parts" (vs/jt
                  "public"
                  "cancelTransaction")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "check_card_black_listed" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "cardNo"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "check_card_black_listed"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/checkCardBlackListed"
                "parts" (vs/jt
                  "checkCardBlackListed")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "create_product" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "acquirerId"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "templateName"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "templateType"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "templateXml"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalType"
            "req" true
            "type" "`$STRING`"))
        "name" "create_product"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/createProduct"
                "parts" (vs/jt
                  "createProduct")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "deactivate_terminal" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "corporateUuid"
            "type" "`$STRING`")
          (vs/jm
            "name" "deactivationReason"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "packageOrderUuid"
            "type" "`$STRING`")
          (vs/jm
            "name" "productOrderUuid"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalId"
            "req" true
            "type" "`$INTEGER`"))
        "name" "deactivate_terminal"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/deactivateTerminal"
                "parts" (vs/jt
                  "deactivateTerminal")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "digital_services_api" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "clearingDateFrom"
            "req" true
            "short" "Date and time in the format yyyy-MM-dd'T'HH:mm:ssz"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingDateTo"
            "req" true
            "short" "Date and time in the format yyyy-MM-dd'T'HH:mm:ssz"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "txCount"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "txIdEnd"
            "type" "`$STRING`")
          (vs/jm
            "name" "txIdStart"
            "type" "`$STRING`")
          (vs/jm
            "name" "txSeqNoEnd"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "txSeqNoStart"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "txTotal"
            "type" "`$INTEGER`"))
        "name" "digital_services_api"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "file_id"
                      "orig" "file_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/public/digitalservices/mandatorClearingExportDownload/{fileId}"
                "parts" (vs/jt
                  "public"
                  "digitalservices"
                  "mandatorClearingExportDownload"
                  "{file_id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "fileId" "file_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "file_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/digitalservices/mandatorClearingExportMetadata"
                "parts" (vs/jt
                  "public"
                  "digitalservices"
                  "mandatorClearingExportMetadata")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/public/digitalservices/mandatorClearingExportDownload/status"
                "parts" (vs/jt
                  "public"
                  "digitalservices"
                  "mandatorClearingExportDownload"
                  "status")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "mandator_clearing_export_download"))))
      "ec_data_ecom" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "ecomData"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalId"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "transactionId"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionType"
            "req" true
            "type" "`$STRING`"))
        "name" "ec_data_ecom"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/getEcData"
                "parts" (vs/jt
                  "public"
                  "getEcData")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "ecom_parameter" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "ecomPass"
            "type" "`$STRING`")
          (vs/jm
            "name" "ecomSkey"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalId"
            "req" true
            "type" "`$INTEGER`"))
        "name" "ecom_parameter"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/getEcomParameters"
                "parts" (vs/jt
                  "public"
                  "getEcomParameters")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "ecr_data" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "ecrData"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalId"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "transactionId"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionType"
            "req" true
            "type" "`$STRING`"))
        "name" "ecr_data"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/getEcrData"
                "parts" (vs/jt
                  "public"
                  "getEcrData")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "emv_data" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "emvData"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalId"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "transactionId"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionType"
            "req" true
            "type" "`$STRING`"))
        "name" "emv_data"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/getEmvData"
                "parts" (vs/jt
                  "public"
                  "getEmvData")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "enable_acquiring" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "accountNo"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "additionalData"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "corporateUuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "currency"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "merchantCategoryCode"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "packageOrderUuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "productOrderUuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "sortingCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "templateName"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalIdAcq"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalIds"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "vuNummer"
            "type" "`$STRING`"))
        "name" "enable_acquiring"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/enableAcquiring"
                "parts" (vs/jt
                  "enableAcquiring")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "get_merchant_contract_number" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "merchantContractNumber"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "get_merchant_contract_number"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/getMerchantContractNumber"
                "parts" (vs/jt
                  "getMerchantContractNumber")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "get_template_xml" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "templateName"
            "req" true
            "type" "`$STRING`"))
        "name" "get_template_xml"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/getTemplateXml"
                "parts" (vs/jt
                  "public"
                  "getTemplateXml")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "introduce_mandator" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "mandatorName"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "introduce_mandator"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/introduceMandator"
                "parts" (vs/jt
                  "introduceMandator")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "introduce_package" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalTemplateDescription"
            "req" true
            "type" "`$STRING`"))
        "name" "introduce_package"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/introducePackage"
                "parts" (vs/jt
                  "introducePackage")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "keep_alive" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "hwserialno"
            "type" "`$STRING`")
          (vs/jm
            "name" "kaDateTimeFrom"
            "type" "`$STRING`")
          (vs/jm
            "name" "kaDateTimeTo"
            "type" "`$STRING`")
          (vs/jm
            "name" "keepAliveData"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "pagination"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalDateTimeFrom"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalDateTimeTo"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalId"
            "type" "`$INTEGER`"))
        "name" "keep_alive"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/keepalive"
                "parts" (vs/jt
                  "public"
                  "keepalive")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "list_terminal" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "corporateUuid"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "filter"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "pagination"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminals"
            "type" "`$ARRAY`"))
        "name" "list_terminal"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/listTerminals"
                "parts" (vs/jt
                  "public"
                  "listTerminals")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "mandator_clearing_export" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "clearingDateFrom"
            "req" true
            "short" "Date and time in the format yyyy-MM-dd'T'HH:mm:ssZ"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingDateTo"
            "req" true
            "short" "Date and time in the format yyyy-MM-dd'T'HH:mm:ssZ"
            "type" "`$STRING`")
          (vs/jm
            "name" "pagination"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "records"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "mandator_clearing_export"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/digitalservices/mandatorClearingExport"
                "parts" (vs/jt
                  "public"
                  "digitalservices"
                  "mandatorClearingExport")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "mandator_clearing_export_download" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "clearingDateFrom"
            "req" true
            "short" "Start date for clearing export (inclusive)"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingDateTo"
            "req" true
            "short" "End date for clearing export (inclusive)"
            "type" "`$STRING`")
          (vs/jm
            "name" "fileId"
            "short" "Unique file identifier for tracking and downloading"
            "type" "`$STRING`")
          (vs/jm
            "name" "filenameTemplate"
            "short" "Optional filename template for the export file"
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "status"
            "short" "Processing status of the export request"
            "type" "`$STRING`"))
        "name" "mandator_clearing_export_download"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/digitalservices/mandatorClearingExportDownload"
                "parts" (vs/jt
                  "public"
                  "digitalservices"
                  "mandatorClearingExportDownload")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "file_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/public/digitalservices/mandatorClearingExportDownload/{fileId}"
                "parts" (vs/jt
                  "public"
                  "digitalservices"
                  "mandatorClearingExportDownload"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "fileId" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "mandator_clearing_export_summary" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "clearingDateFrom"
            "req" true
            "short" "Date and time in the format yyyy-MM-dd'T'HH:mm:ssz"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingDateTo"
            "req" true
            "short" "Date and time in the format yyyy-MM-dd'T'HH:mm:ssz"
            "type" "`$STRING`")
          (vs/jm
            "name" "records"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "mandator_clearing_export_summary"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/digitalservices/mandatorClearingExportSummary"
                "parts" (vs/jt
                  "public"
                  "digitalservices"
                  "mandatorClearingExportSummary")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "merchant_portal_services_api" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "3DSecure"
            "type" "`$STRING`")
          (vs/jm
            "name" "authorizationCode"
            "type" "`$STRING`")
          (vs/jm
            "name" "cardBrand"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingAmountFrom"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingAmountTo"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingCurrency"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingStatus"
            "type" "`$STRING`")
          (vs/jm
            "name" "corporateUUID"
            "type" "`$STRING`")
          (vs/jm
            "name" "orderByTransactionDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "pagination"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "receiptNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "referencedTransactionId"
            "type" "`$STRING`")
          (vs/jm
            "name" "retrievalReferenceNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "sourceId"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "tecsengineResponseCodeFrom"
            "type" "`$STRING`")
          (vs/jm
            "name" "tecsengineResponseCodeTo"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalId"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "traceNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionAmountFrom"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionAmountTo"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionDateFrom"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionDateTo"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionId"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionType"
            "type" "`$STRING`")
          (vs/jm
            "name" "wallet"
            "short" "Filter by wallet type."
            "type" "`$STRING`"))
        "name" "merchant_portal_services_api"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/transactionHistoryCsv"
                "parts" (vs/jt
                  "public"
                  "transactionHistoryCsv")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "move_tid" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "productorderuuids"
            "req" true
            "type" "`$ARRAY`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "targetPackageorderuuid"
            "type" "`$STRING`")
          (vs/jm
            "name" "targetProductorderuuid"
            "type" "`$STRING`"))
        "name" "move_tid"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/moveTid"
                "parts" (vs/jt
                  "moveTid")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "payment_manual" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "acquirerName"
            "short" "Acquirer name parsed from KKG field"
            "type" "`$STRING`")
          (vs/jm
            "name" "amount"
            "req" true
            "short" "Transaction amount in minor units (cents)"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "authorizationNumber"
            "short" "Authorization number from the gateway"
            "type" "`$STRING`")
          (vs/jm
            "name" "cardNumber"
            "req" true
            "short" "Card number - 12 to 19 digits, must pass Luhn validation"
            "type" "`$STRING`")
          (vs/jm
            "name" "cardType"
            "short" "Card type parsed from KKG field"
            "type" "`$STRING`")
          (vs/jm
            "name" "currency"
            "req" true
            "short" "Currency code - 3 uppercase letters (ISO 4217)"
            "type" "`$STRING`")
          (vs/jm
            "name" "cvc"
            "short" "Card verification code - 3-4 digits (optional)"
            "type" "`$STRING`")
          (vs/jm
            "name" "dateTimeTx"
            "short" "Date and time of the transaction"
            "type" "`$STRING`")
          (vs/jm
            "name" "expDate"
            "req" true
            "short" "Card expiry date in MMYY format"
            "type" "`$STRING`")
          (vs/jm
            "name" "merchantId"
            "short" "Merchant ID (VU-NUMMER)"
            "type" "`$STRING`")
          (vs/jm
            "name" "originalTransactionId"
            "short" "Original transaction ID from gateway"
            "type" "`$STRING`")
          (vs/jm
            "name" "password"
            "short" "Terminal password sent as Kennwort in TECS XML (optional)"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "short" "Response code - 00 for success, otherwise error code"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseMessage"
            "short" "Response message - 'Approved' for success, error description otherwise"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalId"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "short" "Terminal ID used for the transaction"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionId"
            "short" "Transaction ID generated by the backend"
            "type" "`$STRING`")
          (vs/jm
            "name" "txtype"
            "req" true
            "short" "Transaction type"
            "type" "`$STRING`"))
        "name" "payment_manual"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/paymentManual"
                "parts" (vs/jt
                  "public"
                  "paymentManual")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "payment_sred" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "amount"
            "req" true
            "short" "Transaction amount in minor units (cents)"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "currency"
            "req" true
            "short" "Currency code - 3 uppercase letters (ISO 4217)"
            "type" "`$STRING`")
          (vs/jm
            "name" "device"
            "short" "Device type that provided the SRED payload"
            "type" "`$STRING`")
          (vs/jm
            "name" "devicePayload"
            "req" true
            "short" "SRED encrypted device payload from the device (minimum 32 characters)"
            "type" "`$STRING`")
          (vs/jm
            "name" "expDate"
            "short" "Card expiry date in MMYY format"
            "type" "`$STRING`")
          (vs/jm
            "name" "mode"
            "short" "Decryption mode"
            "type" "`$STRING`")
          (vs/jm
            "name" "panMasked"
            "short" "Masked PAN (first 6 and last 4 digits)"
            "type" "`$STRING`")
          (vs/jm
            "name" "password"
            "short" "Terminal password sent as Kennwort in TECS XML (optional)"
            "type" "`$STRING`")
          (vs/jm
            "name" "serial"
            "short" "Device serial number"
            "type" "`$STRING`")
          (vs/jm
            "name" "serviceCode"
            "short" "Service code from the card"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalId"
            "req" true
            "short" "Terminal ID - 8 digits"
            "type" "`$STRING`")
          (vs/jm
            "name" "txtype"
            "req" true
            "short" "Transaction type"
            "type" "`$STRING`"))
        "name" "payment_sred"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/paymentSred"
                "parts" (vs/jt
                  "public"
                  "paymentSred")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.sred`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "pre_auth_transaction_completion" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "acquirerId"
            "type" "`$STRING`")
          (vs/jm
            "name" "acquirerName"
            "type" "`$STRING`")
          (vs/jm
            "name" "actualBonusPoints"
            "type" "`$STRING`")
          (vs/jm
            "name" "amount"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$INTEGER`"))
            "type" "`$INTEGER`")
          (vs/jm
            "name" "authorizationCode"
            "type" "`$STRING`")
          (vs/jm
            "name" "balanceAmount"
            "type" "`$STRING`")
          (vs/jm
            "name" "cardBrand"
            "type" "`$STRING`")
          (vs/jm
            "name" "cardNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "cardNumberReference"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "clientId"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "currency"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "cvc"
            "type" "`$STRING`")
          (vs/jm
            "name" "ecData"
            "type" "`$STRING`")
          (vs/jm
            "name" "ecrData"
            "type" "`$STRING`")
          (vs/jm
            "name" "emvData"
            "type" "`$STRING`")
          (vs/jm
            "name" "exchangeFee"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "exchangeRate"
            "type" "`$STRING`")
          (vs/jm
            "name" "languageCode"
            "type" "`$STRING`")
          (vs/jm
            "name" "merchantAddress"
            "type" "`$STRING`")
          (vs/jm
            "name" "merchantName"
            "type" "`$STRING`")
          (vs/jm
            "name" "merchantNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "messageType"
            "type" "`$STRING`")
          (vs/jm
            "name" "originalTraceNumber"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "originalTransactionId"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "password"
            "type" "`$STRING`")
          (vs/jm
            "name" "paymentReason"
            "type" "`$STRING`")
          (vs/jm
            "name" "receiptFooter"
            "type" "`$STRING`")
          (vs/jm
            "name" "receiptHeader"
            "type" "`$STRING`")
          (vs/jm
            "name" "receiptLayout"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "receiptNumber"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "serialNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "svc"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalId"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "terminalLocation"
            "type" "`$STRING`")
          (vs/jm
            "name" "traceNumber"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "transactionDate"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionId"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionType"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "txType"
            "type" "`$STRING`")
          (vs/jm
            "name" "userData"
            "type" "`$STRING`"))
        "name" "pre_auth_transaction_completion"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/paymentTransaction"
                "parts" (vs/jt
                  "public"
                  "paymentTransaction")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/preAuthCompletionTransaction"
                "parts" (vs/jt
                  "public"
                  "preAuthCompletionTransaction")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "reactivate_terminal" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "corporateUuid"
            "type" "`$STRING`")
          (vs/jm
            "name" "packageOrderUuid"
            "type" "`$STRING`")
          (vs/jm
            "name" "productOrderUuid"
            "type" "`$STRING`")
          (vs/jm
            "name" "reactivationReason"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalId"
            "req" true
            "type" "`$INTEGER`"))
        "name" "reactivate_terminal"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/reactivateTerminal"
                "parts" (vs/jt
                  "reactivateTerminal")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "refund_transaction" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "acquirerId"
            "type" "`$STRING`")
          (vs/jm
            "name" "acquirerName"
            "type" "`$STRING`")
          (vs/jm
            "name" "actualBonusPoints"
            "type" "`$STRING`")
          (vs/jm
            "name" "amount"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$INTEGER`"))
            "type" "`$INTEGER`")
          (vs/jm
            "name" "authorizationCode"
            "type" "`$STRING`")
          (vs/jm
            "name" "balanceAmount"
            "type" "`$STRING`")
          (vs/jm
            "name" "cardBrand"
            "type" "`$STRING`")
          (vs/jm
            "name" "cardNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "clientId"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "currency"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "cvc"
            "type" "`$STRING`")
          (vs/jm
            "name" "ecData"
            "type" "`$STRING`")
          (vs/jm
            "name" "ecrData"
            "type" "`$STRING`")
          (vs/jm
            "name" "emvData"
            "type" "`$STRING`")
          (vs/jm
            "name" "exchangeFee"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "exchangeRate"
            "type" "`$STRING`")
          (vs/jm
            "name" "languageCode"
            "type" "`$STRING`")
          (vs/jm
            "name" "merchantAddress"
            "type" "`$STRING`")
          (vs/jm
            "name" "merchantName"
            "type" "`$STRING`")
          (vs/jm
            "name" "merchantNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "messageType"
            "type" "`$STRING`")
          (vs/jm
            "name" "originalTraceNumber"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "originalTransactionId"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "password"
            "type" "`$STRING`")
          (vs/jm
            "name" "paymentReason"
            "type" "`$STRING`")
          (vs/jm
            "name" "receiptFooter"
            "type" "`$STRING`")
          (vs/jm
            "name" "receiptHeader"
            "type" "`$STRING`")
          (vs/jm
            "name" "receiptLayout"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "receiptNumber"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "serialNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "svc"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalId"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "terminalLocation"
            "type" "`$STRING`")
          (vs/jm
            "name" "traceNumber"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "transactionDate"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionId"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "txType"
            "type" "`$STRING`")
          (vs/jm
            "name" "userData"
            "type" "`$STRING`"))
        "name" "refund_transaction"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/refundTransaction"
                "parts" (vs/jt
                  "public"
                  "refundTransaction")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "register_tecs_company" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "corporateUuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "packageOrderUuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "partnerId"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "partnerName"
            "type" "`$STRING`")
          (vs/jm
            "name" "productOrderUuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "templateName"
            "req" true
            "type" "`$STRING`"))
        "name" "register_tecs_company"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/registerTecsCompany"
                "parts" (vs/jt
                  "registerTecsCompany")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "register_terminal" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "additionalData"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "corporateUuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "packageOrderUuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "productOrderUuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "tecsWebSecretKey"
            "type" "`$STRING`")
          (vs/jm
            "name" "templateName"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalCountryCode"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalId"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "terminalIdAcq"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalLanguageCode"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalLocation"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalSerialNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "tokenIOAlias"
            "type" "`$STRING`")
          (vs/jm
            "name" "tokenIOIban"
            "type" "`$STRING`")
          (vs/jm
            "name" "tokenIOMemberId"
            "type" "`$STRING`")
          (vs/jm
            "name" "webShopUrl"
            "type" "`$STRING`"))
        "name" "register_terminal"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/registerTerminal"
                "parts" (vs/jt
                  "registerTerminal")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "report_data" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "cardBrandReportData"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "clearingDateFrom"
            "req" true
            "short" "Date and time in the format yyyy-MM-dd'T'HH:mm:ss"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingDateTo"
            "req" true
            "short" "Date and time in the format yyyy-MM-dd'T'HH:mm:ss"
            "type" "`$STRING`")
          (vs/jm
            "name" "corporateId"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "currency"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "sumOverCreditTx"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "sumOverDebitTx"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "terminalId"
            "type" "`$INTEGER`"))
        "name" "report_data"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/digitalservices/reportData"
                "parts" (vs/jt
                  "public"
                  "digitalservices"
                  "reportData")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "status_transaction" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "acquirerName"
            "type" "`$STRING`")
          (vs/jm
            "name" "acquirerTerminalId"
            "type" "`$STRING`")
          (vs/jm
            "name" "amount"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "applicationCryptogram"
            "type" "`$STRING`")
          (vs/jm
            "name" "authorizationCode"
            "short" "Authorization code returned by the acquirer; null when not available"
            "type" (vs/jt
              "`$ONE`"
              (vs/jt
                "`$STRING`"
                "`$NULL`")))
          (vs/jm
            "name" "authorizationDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "cardBrand"
            "type" "`$STRING`")
          (vs/jm
            "name" "cardEntry"
            "type" "`$STRING`")
          (vs/jm
            "name" "cardExpiration"
            "type" "`$STRING`")
          (vs/jm
            "name" "cardNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingAmount"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "clearingBatchId"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingCurrency"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingProcessedDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingStatus"
            "type" "`$STRING`")
          (vs/jm
            "name" "clientId"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "currency"
            "type" "`$STRING`")
          (vs/jm
            "name" "cvm"
            "type" "`$STRING`")
          (vs/jm
            "name" "ecrData"
            "type" "`$STRING`")
          (vs/jm
            "name" "emvApplicationId"
            "type" "`$STRING`")
          (vs/jm
            "name" "emvApplicationLabel"
            "type" "`$STRING`")
          (vs/jm
            "name" "merchantName"
            "type" "`$STRING`")
          (vs/jm
            "name" "merchantNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "originalClientId"
            "type" "`$STRING`")
          (vs/jm
            "name" "originalTerminalId"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "originalTransactionId"
            "type" "`$STRING`")
          (vs/jm
            "name" "paymentReason"
            "type" "`$STRING`")
          (vs/jm
            "name" "receiptNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseCodeFromAS"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "retrievalReferenceNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "serviceCode"
            "type" "`$STRING`")
          (vs/jm
            "name" "settlementStatus"
            "type" "`$STRING`")
          (vs/jm
            "name" "sourceId"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "tecsengineResponseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "tecsengineResponseText"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalEndOfDayDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalId"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "terminalLocation"
            "type" "`$STRING`")
          (vs/jm
            "name" "tipAmount"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "traceNumber"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "transactionClearingDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionId"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionSeqNumber"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "transactionServerDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionSource"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionType"
            "type" "`$STRING`"))
        "name" "status_transaction"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/statusTransaction"
                "parts" (vs/jt
                  "public"
                  "statusTransaction")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "store_terminal_parameter" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "acqTabNexo"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "configVersion"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "serialNumber"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "tidSent"
            "type" "`$STRING`"))
        "name" "store_terminal_parameter"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/storeTerminalParameters"
                "parts" (vs/jt
                  "storeTerminalParameters")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "terminal_id" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "deviceSerialNumber"
            "req" true
            "type" "`$ARRAY`")
          (vs/jm
            "name" "duplicateTerminalIds"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminals"
            "type" "`$ARRAY`"))
        "name" "terminal_id"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/getTerminalId"
                "parts" (vs/jt
                  "public"
                  "getTerminalId")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "transaction_history" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "3DSecure"
            "type" "`$STRING`")
          (vs/jm
            "name" "authorizationCode"
            "type" "`$STRING`")
          (vs/jm
            "name" "cardBrand"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingAmountFrom"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingAmountTo"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingCurrency"
            "type" "`$STRING`")
          (vs/jm
            "name" "clearingStatus"
            "type" "`$STRING`")
          (vs/jm
            "name" "corporateUUID"
            "type" "`$STRING`")
          (vs/jm
            "name" "orderByTransactionDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "pagination"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "paymentTokenPublicId"
            "type" "`$STRING`")
          (vs/jm
            "name" "receiptNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "referencedTransactionId"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "retrievalReferenceNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "sourceId"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "tecsengineResponseCodeFrom"
            "type" "`$STRING`")
          (vs/jm
            "name" "tecsengineResponseCodeTo"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalId"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "traceNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionAmountFrom"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionAmountTo"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionDateFrom"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionDateTo"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionHistories"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "transactionId"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionType"
            "type" "`$STRING`")
          (vs/jm
            "name" "wallet"
            "short" "Filter by wallet type."
            "type" "`$STRING`"))
        "name" "transaction_history"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/mcom/transactionHistory"
                "parts" (vs/jt
                  "public"
                  "mcom"
                  "transactionHistory")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/transactionHistory"
                "parts" (vs/jt
                  "public"
                  "transactionHistory")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "transactions_count" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "period"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionDateFrom"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionDateTo"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionsCount"
            "type" "`$ARRAY`"))
        "name" "transactions_count"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/countAuthorisedTransactions"
                "parts" (vs/jt
                  "public"
                  "countAuthorisedTransactions")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/countNotAuthorisedTransactions"
                "parts" (vs/jt
                  "public"
                  "countNotAuthorisedTransactions")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "transactions_count_card_brand" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "period"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionDateFrom"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionDateTo"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionsCount"
            "type" "`$ARRAY`"))
        "name" "transactions_count_card_brand"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/countTransactionsByCardBrand"
                "parts" (vs/jt
                  "public"
                  "countTransactionsByCardBrand")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "transactions_turnover" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "period"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionDateFrom"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionDateTo"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "turnovers"
            "type" "`$ARRAY`"))
        "name" "transactions_turnover"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/transactionTurnover"
                "parts" (vs/jt
                  "public"
                  "transactionTurnover")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "update_merchant" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "city"
            "type" "`$STRING`")
          (vs/jm
            "name" "corporateUuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "country"
            "type" "`$STRING`")
          (vs/jm
            "name" "merchantCategoryCode"
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "state"
            "type" "`$STRING`")
          (vs/jm
            "name" "street"
            "type" "`$STRING`")
          (vs/jm
            "name" "vuNummer"
            "type" "`$STRING`")
          (vs/jm
            "name" "zipcode"
            "type" "`$STRING`"))
        "name" "update_merchant"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/updateMerchant"
                "parts" (vs/jt
                  "public"
                  "updateMerchant")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "update_template_xml" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "templateName"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "templateXml"
            "req" true
            "type" "`$STRING`"))
        "name" "update_template_xml"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/public/updateTemplateXml"
                "parts" (vs/jt
                  "public"
                  "updateTemplateXml")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "version" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "appName"
            "type" "`$STRING`")
          (vs/jm
            "name" "buildDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "type" "`$STRING`"))
        "name" "version"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/public/version"
                "parts" (vs/jt
                  "public"
                  "version")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)
        "transport" "base"))
    "main" (vs/jm
      "name" "BluefinTecsMerchantServices"
      "slug" "bluefin-tecs-merchant-services"
      "target" "clojure"
      "version" "0.1.1")
    "options" (vs/jm
      "auth" (vs/jm
        "prefix" "Bearer")
      "base" "https://test.tecs.at/merchantservices"
      "entity" (vs/jm
        "cancel_transaction" (vs/jm)
        "check_card_black_listed" (vs/jm)
        "create_product" (vs/jm)
        "deactivate_terminal" (vs/jm)
        "digital_services_api" (vs/jm)
        "ec_data_ecom" (vs/jm)
        "ecom_parameter" (vs/jm)
        "ecr_data" (vs/jm)
        "emv_data" (vs/jm)
        "enable_acquiring" (vs/jm)
        "get_merchant_contract_number" (vs/jm)
        "get_template_xml" (vs/jm)
        "introduce_mandator" (vs/jm)
        "introduce_package" (vs/jm)
        "keep_alive" (vs/jm)
        "list_terminal" (vs/jm)
        "mandator_clearing_export" (vs/jm)
        "mandator_clearing_export_download" (vs/jm)
        "mandator_clearing_export_summary" (vs/jm)
        "merchant_portal_services_api" (vs/jm)
        "move_tid" (vs/jm)
        "payment_manual" (vs/jm)
        "payment_sred" (vs/jm)
        "pre_auth_transaction_completion" (vs/jm)
        "reactivate_terminal" (vs/jm)
        "refund_transaction" (vs/jm)
        "register_tecs_company" (vs/jm)
        "register_terminal" (vs/jm)
        "report_data" (vs/jm)
        "status_transaction" (vs/jm)
        "store_terminal_parameter" (vs/jm)
        "terminal_id" (vs/jm)
        "transaction_history" (vs/jm)
        "transactions_count" (vs/jm)
        "transactions_count_card_brand" (vs/jm)
        "transactions_turnover" (vs/jm)
        "update_merchant" (vs/jm)
        "update_template_xml" (vs/jm)
        "version" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
